// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateAccountingProjectQueryParamFields string

const (
	CreateAccountingProjectQueryParamFieldsID                   CreateAccountingProjectQueryParamFields = "id"
	CreateAccountingProjectQueryParamFieldsCreatedAt            CreateAccountingProjectQueryParamFields = "created_at"
	CreateAccountingProjectQueryParamFieldsUpdatedAt            CreateAccountingProjectQueryParamFields = "updated_at"
	CreateAccountingProjectQueryParamFieldsName                 CreateAccountingProjectQueryParamFields = "name"
	CreateAccountingProjectQueryParamFieldsCode                 CreateAccountingProjectQueryParamFields = "code"
	CreateAccountingProjectQueryParamFieldsDescription          CreateAccountingProjectQueryParamFields = "description"
	CreateAccountingProjectQueryParamFieldsStatus               CreateAccountingProjectQueryParamFields = "status"
	CreateAccountingProjectQueryParamFieldsIsActive             CreateAccountingProjectQueryParamFields = "is_active"
	CreateAccountingProjectQueryParamFieldsIsBillable           CreateAccountingProjectQueryParamFields = "is_billable"
	CreateAccountingProjectQueryParamFieldsContactID            CreateAccountingProjectQueryParamFields = "contact_id"
	CreateAccountingProjectQueryParamFieldsParentID             CreateAccountingProjectQueryParamFields = "parent_id"
	CreateAccountingProjectQueryParamFieldsManagerUserID        CreateAccountingProjectQueryParamFields = "manager_user_id"
	CreateAccountingProjectQueryParamFieldsStartedAt            CreateAccountingProjectQueryParamFields = "started_at"
	CreateAccountingProjectQueryParamFieldsDueAt                CreateAccountingProjectQueryParamFields = "due_at"
	CreateAccountingProjectQueryParamFieldsEndedAt              CreateAccountingProjectQueryParamFields = "ended_at"
	CreateAccountingProjectQueryParamFieldsCurrency             CreateAccountingProjectQueryParamFields = "currency"
	CreateAccountingProjectQueryParamFieldsEstimateAmount       CreateAccountingProjectQueryParamFields = "estimate_amount"
	CreateAccountingProjectQueryParamFieldsEstimatedCostAmount  CreateAccountingProjectQueryParamFields = "estimated_cost_amount"
	CreateAccountingProjectQueryParamFieldsActualCostAmount     CreateAccountingProjectQueryParamFields = "actual_cost_amount"
	CreateAccountingProjectQueryParamFieldsInvoicedAmount       CreateAccountingProjectQueryParamFields = "invoiced_amount"
	CreateAccountingProjectQueryParamFieldsToBeInvoicedAmount   CreateAccountingProjectQueryParamFields = "to_be_invoiced_amount"
	CreateAccountingProjectQueryParamFieldsExpenseAmount        CreateAccountingProjectQueryParamFields = "expense_amount"
	CreateAccountingProjectQueryParamFieldsDepositAmount        CreateAccountingProjectQueryParamFields = "deposit_amount"
	CreateAccountingProjectQueryParamFieldsDepositAppliedAmount CreateAccountingProjectQueryParamFields = "deposit_applied_amount"
	CreateAccountingProjectQueryParamFieldsCreditNoteAmount     CreateAccountingProjectQueryParamFields = "credit_note_amount"
	CreateAccountingProjectQueryParamFieldsMinutesLogged        CreateAccountingProjectQueryParamFields = "minutes_logged"
	CreateAccountingProjectQueryParamFieldsMinutesToBeInvoiced  CreateAccountingProjectQueryParamFields = "minutes_to_be_invoiced"
	CreateAccountingProjectQueryParamFieldsPercentComplete      CreateAccountingProjectQueryParamFields = "percent_complete"
	CreateAccountingProjectQueryParamFieldsBillingType          CreateAccountingProjectQueryParamFields = "billing_type"
	CreateAccountingProjectQueryParamFieldsCategoryIds          CreateAccountingProjectQueryParamFields = "category_ids"
	CreateAccountingProjectQueryParamFieldsLocationID           CreateAccountingProjectQueryParamFields = "location_id"
	CreateAccountingProjectQueryParamFieldsOrganizationID       CreateAccountingProjectQueryParamFields = "organization_id"
	CreateAccountingProjectQueryParamFieldsRaw                  CreateAccountingProjectQueryParamFields = "raw"
)

func (e CreateAccountingProjectQueryParamFields) ToPointer() *CreateAccountingProjectQueryParamFields {
	return &e
}
func (e *CreateAccountingProjectQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "code":
		fallthrough
	case "description":
		fallthrough
	case "status":
		fallthrough
	case "is_active":
		fallthrough
	case "is_billable":
		fallthrough
	case "contact_id":
		fallthrough
	case "parent_id":
		fallthrough
	case "manager_user_id":
		fallthrough
	case "started_at":
		fallthrough
	case "due_at":
		fallthrough
	case "ended_at":
		fallthrough
	case "currency":
		fallthrough
	case "estimate_amount":
		fallthrough
	case "estimated_cost_amount":
		fallthrough
	case "actual_cost_amount":
		fallthrough
	case "invoiced_amount":
		fallthrough
	case "to_be_invoiced_amount":
		fallthrough
	case "expense_amount":
		fallthrough
	case "deposit_amount":
		fallthrough
	case "deposit_applied_amount":
		fallthrough
	case "credit_note_amount":
		fallthrough
	case "minutes_logged":
		fallthrough
	case "minutes_to_be_invoiced":
		fallthrough
	case "percent_complete":
		fallthrough
	case "billing_type":
		fallthrough
	case "category_ids":
		fallthrough
	case "location_id":
		fallthrough
	case "organization_id":
		fallthrough
	case "raw":
		*e = CreateAccountingProjectQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateAccountingProjectQueryParamFields: %v", v)
	}
}

type CreateAccountingProjectRequest struct {
	AccountingProject shared.AccountingProject `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []CreateAccountingProjectQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateAccountingProjectRequest) GetAccountingProject() shared.AccountingProject {
	if c == nil {
		return shared.AccountingProject{}
	}
	return c.AccountingProject
}

func (c *CreateAccountingProjectRequest) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateAccountingProjectRequest) GetFields() []CreateAccountingProjectQueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateAccountingProjectRequest) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

type CreateAccountingProjectResponse struct {
	// Successful
	AccountingProject *shared.AccountingProject
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateAccountingProjectResponse) GetAccountingProject() *shared.AccountingProject {
	if c == nil {
		return nil
	}
	return c.AccountingProject
}

func (c *CreateAccountingProjectResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateAccountingProjectResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateAccountingProjectResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
