// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateAtsScorecard2QueryParamFields string

const (
	CreateAtsScorecard2QueryParamFieldsID             CreateAtsScorecard2QueryParamFields = "id"
	CreateAtsScorecard2QueryParamFieldsCreatedAt      CreateAtsScorecard2QueryParamFields = "created_at"
	CreateAtsScorecard2QueryParamFieldsUpdatedAt      CreateAtsScorecard2QueryParamFields = "updated_at"
	CreateAtsScorecard2QueryParamFieldsApplicationID  CreateAtsScorecard2QueryParamFields = "application_id"
	CreateAtsScorecard2QueryParamFieldsInterviewerID  CreateAtsScorecard2QueryParamFields = "interviewer_id"
	CreateAtsScorecard2QueryParamFieldsInterviewID    CreateAtsScorecard2QueryParamFields = "interview_id"
	CreateAtsScorecard2QueryParamFieldsCandidateID    CreateAtsScorecard2QueryParamFields = "candidate_id"
	CreateAtsScorecard2QueryParamFieldsJobID          CreateAtsScorecard2QueryParamFields = "job_id"
	CreateAtsScorecard2QueryParamFieldsRecommendation CreateAtsScorecard2QueryParamFields = "recommendation"
	CreateAtsScorecard2QueryParamFieldsComment        CreateAtsScorecard2QueryParamFields = "comment"
	CreateAtsScorecard2QueryParamFieldsQuestions      CreateAtsScorecard2QueryParamFields = "questions"
	CreateAtsScorecard2QueryParamFieldsRaw            CreateAtsScorecard2QueryParamFields = "raw"
)

func (e CreateAtsScorecard2QueryParamFields) ToPointer() *CreateAtsScorecard2QueryParamFields {
	return &e
}
func (e *CreateAtsScorecard2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "application_id":
		fallthrough
	case "interviewer_id":
		fallthrough
	case "interview_id":
		fallthrough
	case "candidate_id":
		fallthrough
	case "job_id":
		fallthrough
	case "recommendation":
		fallthrough
	case "comment":
		fallthrough
	case "questions":
		fallthrough
	case "raw":
		*e = CreateAtsScorecard2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateAtsScorecard2QueryParamFields: %v", v)
	}
}

type CreateAtsScorecard2Request struct {
	AtsScorecard shared.AtsScorecard `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []CreateAtsScorecard2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateAtsScorecard2Request) GetAtsScorecard() shared.AtsScorecard {
	if c == nil {
		return shared.AtsScorecard{}
	}
	return c.AtsScorecard
}

func (c *CreateAtsScorecard2Request) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateAtsScorecard2Request) GetFields() []CreateAtsScorecard2QueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateAtsScorecard2Request) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

// #region class-body-createatsscorecard2request
// #endregion class-body-createatsscorecard2request

type CreateAtsScorecard2Response struct {
	// Successful
	AtsScorecard *shared.AtsScorecard
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateAtsScorecard2Response) GetAtsScorecard() *shared.AtsScorecard {
	if c == nil {
		return nil
	}
	return c.AtsScorecard
}

func (c *CreateAtsScorecard2Response) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateAtsScorecard2Response) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateAtsScorecard2Response) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-createatsscorecard2response
// #endregion class-body-createatsscorecard2response
