// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateUcComment2QueryParamFields string

const (
	CreateUcComment2QueryParamFieldsID        CreateUcComment2QueryParamFields = "id"
	CreateUcComment2QueryParamFieldsCreatedAt CreateUcComment2QueryParamFields = "created_at"
	CreateUcComment2QueryParamFieldsUpdatedAt CreateUcComment2QueryParamFields = "updated_at"
	CreateUcComment2QueryParamFieldsContent   CreateUcComment2QueryParamFields = "content"
	CreateUcComment2QueryParamFieldsUserID    CreateUcComment2QueryParamFields = "user_id"
	CreateUcComment2QueryParamFieldsCallID    CreateUcComment2QueryParamFields = "call_id"
	CreateUcComment2QueryParamFieldsRaw       CreateUcComment2QueryParamFields = "raw"
)

func (e CreateUcComment2QueryParamFields) ToPointer() *CreateUcComment2QueryParamFields {
	return &e
}
func (e *CreateUcComment2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "content":
		fallthrough
	case "user_id":
		fallthrough
	case "call_id":
		fallthrough
	case "raw":
		*e = CreateUcComment2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateUcComment2QueryParamFields: %v", v)
	}
}

type CreateUcComment2Request struct {
	UcComment shared.UcComment `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []CreateUcComment2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateUcComment2Request) GetUcComment() shared.UcComment {
	if c == nil {
		return shared.UcComment{}
	}
	return c.UcComment
}

func (c *CreateUcComment2Request) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateUcComment2Request) GetFields() []CreateUcComment2QueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateUcComment2Request) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

// #region class-body-createuccomment2request
// #endregion class-body-createuccomment2request

type CreateUcComment2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful
	UcComment *shared.UcComment
}

func (c *CreateUcComment2Response) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateUcComment2Response) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateUcComment2Response) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateUcComment2Response) GetUcComment() *shared.UcComment {
	if c == nil {
		return nil
	}
	return c.UcComment
}

// #region class-body-createuccomment2response
// #endregion class-body-createuccomment2response
