// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateMartechMemberQueryParamFields string

const (
	CreateMartechMemberQueryParamFieldsID        CreateMartechMemberQueryParamFields = "id"
	CreateMartechMemberQueryParamFieldsCreatedAt CreateMartechMemberQueryParamFields = "created_at"
	CreateMartechMemberQueryParamFieldsUpdatedAt CreateMartechMemberQueryParamFields = "updated_at"
	CreateMartechMemberQueryParamFieldsName      CreateMartechMemberQueryParamFields = "name"
	CreateMartechMemberQueryParamFieldsFirstName CreateMartechMemberQueryParamFields = "first_name"
	CreateMartechMemberQueryParamFieldsLastName  CreateMartechMemberQueryParamFields = "last_name"
	CreateMartechMemberQueryParamFieldsEmails    CreateMartechMemberQueryParamFields = "emails"
	CreateMartechMemberQueryParamFieldsListIds   CreateMartechMemberQueryParamFields = "list_ids"
	CreateMartechMemberQueryParamFieldsTags      CreateMartechMemberQueryParamFields = "tags"
	CreateMartechMemberQueryParamFieldsRaw       CreateMartechMemberQueryParamFields = "raw"
)

func (e CreateMartechMemberQueryParamFields) ToPointer() *CreateMartechMemberQueryParamFields {
	return &e
}
func (e *CreateMartechMemberQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "first_name":
		fallthrough
	case "last_name":
		fallthrough
	case "emails":
		fallthrough
	case "list_ids":
		fallthrough
	case "tags":
		fallthrough
	case "raw":
		*e = CreateMartechMemberQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateMartechMemberQueryParamFields: %v", v)
	}
}

type CreateMartechMemberRequest struct {
	// A member represents a person
	MarketingMember shared.MarketingMember `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Comma-delimited fields to return
	Fields []CreateMartechMemberQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateMartechMemberRequest) GetMarketingMember() shared.MarketingMember {
	if c == nil {
		return shared.MarketingMember{}
	}
	return c.MarketingMember
}

func (c *CreateMartechMemberRequest) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateMartechMemberRequest) GetFields() []CreateMartechMemberQueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateMartechMemberRequest) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

type CreateMartechMemberResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	MarketingMember *shared.MarketingMember
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateMartechMemberResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateMartechMemberResponse) GetMarketingMember() *shared.MarketingMember {
	if c == nil {
		return nil
	}
	return c.MarketingMember
}

func (c *CreateMartechMemberResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateMartechMemberResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}
