// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateCommerceItem2QueryParamFields string

const (
	CreateCommerceItem2QueryParamFieldsID                CreateCommerceItem2QueryParamFields = "id"
	CreateCommerceItem2QueryParamFieldsCreatedAt         CreateCommerceItem2QueryParamFields = "created_at"
	CreateCommerceItem2QueryParamFieldsUpdatedAt         CreateCommerceItem2QueryParamFields = "updated_at"
	CreateCommerceItem2QueryParamFieldsName              CreateCommerceItem2QueryParamFields = "name"
	CreateCommerceItem2QueryParamFieldsPublicName        CreateCommerceItem2QueryParamFields = "public_name"
	CreateCommerceItem2QueryParamFieldsSlug              CreateCommerceItem2QueryParamFields = "slug"
	CreateCommerceItem2QueryParamFieldsDescription       CreateCommerceItem2QueryParamFields = "description"
	CreateCommerceItem2QueryParamFieldsGlobalCode        CreateCommerceItem2QueryParamFields = "global_code"
	CreateCommerceItem2QueryParamFieldsPublicDescription CreateCommerceItem2QueryParamFields = "public_description"
	CreateCommerceItem2QueryParamFieldsIsActive          CreateCommerceItem2QueryParamFields = "is_active"
	CreateCommerceItem2QueryParamFieldsIsTaxable         CreateCommerceItem2QueryParamFields = "is_taxable"
	CreateCommerceItem2QueryParamFieldsVendorName        CreateCommerceItem2QueryParamFields = "vendor_name"
	CreateCommerceItem2QueryParamFieldsType              CreateCommerceItem2QueryParamFields = "type"
	CreateCommerceItem2QueryParamFieldsIsVisible         CreateCommerceItem2QueryParamFields = "is_visible"
	CreateCommerceItem2QueryParamFieldsIsFeatured        CreateCommerceItem2QueryParamFields = "is_featured"
	CreateCommerceItem2QueryParamFieldsWeight            CreateCommerceItem2QueryParamFields = "weight"
	CreateCommerceItem2QueryParamFieldsWeightUnit        CreateCommerceItem2QueryParamFields = "weight_unit"
	CreateCommerceItem2QueryParamFieldsRequiresShipping  CreateCommerceItem2QueryParamFields = "requires_shipping"
	CreateCommerceItem2QueryParamFieldsPrices            CreateCommerceItem2QueryParamFields = "prices"
	CreateCommerceItem2QueryParamFieldsInventoryID       CreateCommerceItem2QueryParamFields = "inventory_id"
	CreateCommerceItem2QueryParamFieldsTotalStock        CreateCommerceItem2QueryParamFields = "total_stock"
	CreateCommerceItem2QueryParamFieldsVariants          CreateCommerceItem2QueryParamFields = "variants"
	CreateCommerceItem2QueryParamFieldsTags              CreateCommerceItem2QueryParamFields = "tags"
	CreateCommerceItem2QueryParamFieldsMedia             CreateCommerceItem2QueryParamFields = "media"
	CreateCommerceItem2QueryParamFieldsCollectionIds     CreateCommerceItem2QueryParamFields = "collection_ids"
	CreateCommerceItem2QueryParamFieldsAccountID         CreateCommerceItem2QueryParamFields = "account_id"
	CreateCommerceItem2QueryParamFieldsMetadata          CreateCommerceItem2QueryParamFields = "metadata"
	CreateCommerceItem2QueryParamFieldsCollections       CreateCommerceItem2QueryParamFields = "collections"
	CreateCommerceItem2QueryParamFieldsTaxrateID         CreateCommerceItem2QueryParamFields = "taxrate_id"
	CreateCommerceItem2QueryParamFieldsLocationID        CreateCommerceItem2QueryParamFields = "location_id"
	CreateCommerceItem2QueryParamFieldsDuration          CreateCommerceItem2QueryParamFields = "duration"
	CreateCommerceItem2QueryParamFieldsRaw               CreateCommerceItem2QueryParamFields = "raw"
)

func (e CreateCommerceItem2QueryParamFields) ToPointer() *CreateCommerceItem2QueryParamFields {
	return &e
}
func (e *CreateCommerceItem2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "public_name":
		fallthrough
	case "slug":
		fallthrough
	case "description":
		fallthrough
	case "global_code":
		fallthrough
	case "public_description":
		fallthrough
	case "is_active":
		fallthrough
	case "is_taxable":
		fallthrough
	case "vendor_name":
		fallthrough
	case "type":
		fallthrough
	case "is_visible":
		fallthrough
	case "is_featured":
		fallthrough
	case "weight":
		fallthrough
	case "weight_unit":
		fallthrough
	case "requires_shipping":
		fallthrough
	case "prices":
		fallthrough
	case "inventory_id":
		fallthrough
	case "total_stock":
		fallthrough
	case "variants":
		fallthrough
	case "tags":
		fallthrough
	case "media":
		fallthrough
	case "collection_ids":
		fallthrough
	case "account_id":
		fallthrough
	case "metadata":
		fallthrough
	case "collections":
		fallthrough
	case "taxrate_id":
		fallthrough
	case "location_id":
		fallthrough
	case "duration":
		fallthrough
	case "raw":
		*e = CreateCommerceItem2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCommerceItem2QueryParamFields: %v", v)
	}
}

type CreateCommerceItem2Request struct {
	CommerceItem shared.CommerceItem `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []CreateCommerceItem2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateCommerceItem2Request) GetCommerceItem() shared.CommerceItem {
	if c == nil {
		return shared.CommerceItem{}
	}
	return c.CommerceItem
}

func (c *CreateCommerceItem2Request) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateCommerceItem2Request) GetFields() []CreateCommerceItem2QueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateCommerceItem2Request) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

// #region class-body-createcommerceitem2request
// #endregion class-body-createcommerceitem2request

type CreateCommerceItem2Response struct {
	// Successful
	CommerceItem *shared.CommerceItem
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateCommerceItem2Response) GetCommerceItem() *shared.CommerceItem {
	if c == nil {
		return nil
	}
	return c.CommerceItem
}

func (c *CreateCommerceItem2Response) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateCommerceItem2Response) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateCommerceItem2Response) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-createcommerceitem2response
// #endregion class-body-createcommerceitem2response
