// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateCommerceInventory2QueryParamFields string

const (
	CreateCommerceInventory2QueryParamFieldsID            CreateCommerceInventory2QueryParamFields = "id"
	CreateCommerceInventory2QueryParamFieldsUpdatedAt     CreateCommerceInventory2QueryParamFields = "updated_at"
	CreateCommerceInventory2QueryParamFieldsItemID        CreateCommerceInventory2QueryParamFields = "item_id"
	CreateCommerceInventory2QueryParamFieldsItemVariantID CreateCommerceInventory2QueryParamFields = "item_variant_id"
	CreateCommerceInventory2QueryParamFieldsItemOptionID  CreateCommerceInventory2QueryParamFields = "item_option_id"
	CreateCommerceInventory2QueryParamFieldsLocationID    CreateCommerceInventory2QueryParamFields = "location_id"
	CreateCommerceInventory2QueryParamFieldsAvailable     CreateCommerceInventory2QueryParamFields = "available"
	CreateCommerceInventory2QueryParamFieldsRaw           CreateCommerceInventory2QueryParamFields = "raw"
)

func (e CreateCommerceInventory2QueryParamFields) ToPointer() *CreateCommerceInventory2QueryParamFields {
	return &e
}
func (e *CreateCommerceInventory2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "updated_at":
		fallthrough
	case "item_id":
		fallthrough
	case "item_variant_id":
		fallthrough
	case "item_option_id":
		fallthrough
	case "location_id":
		fallthrough
	case "available":
		fallthrough
	case "raw":
		*e = CreateCommerceInventory2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateCommerceInventory2QueryParamFields: %v", v)
	}
}

type CreateCommerceInventory2Request struct {
	CommerceInventory shared.CommerceInventory `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []CreateCommerceInventory2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateCommerceInventory2Request) GetCommerceInventory() shared.CommerceInventory {
	if c == nil {
		return shared.CommerceInventory{}
	}
	return c.CommerceInventory
}

func (c *CreateCommerceInventory2Request) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateCommerceInventory2Request) GetFields() []CreateCommerceInventory2QueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateCommerceInventory2Request) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

// #region class-body-createcommerceinventory2request
// #endregion class-body-createcommerceinventory2request

type CreateCommerceInventory2Response struct {
	// Successful
	CommerceInventory *shared.CommerceInventory
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateCommerceInventory2Response) GetCommerceInventory() *shared.CommerceInventory {
	if c == nil {
		return nil
	}
	return c.CommerceInventory
}

func (c *CreateCommerceInventory2Response) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateCommerceInventory2Response) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateCommerceInventory2Response) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-createcommerceinventory2response
// #endregion class-body-createcommerceinventory2response
