// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateHrisTimeoff2QueryParamFields string

const (
	CreateHrisTimeoff2QueryParamFieldsID             CreateHrisTimeoff2QueryParamFields = "id"
	CreateHrisTimeoff2QueryParamFieldsCreatedAt      CreateHrisTimeoff2QueryParamFields = "created_at"
	CreateHrisTimeoff2QueryParamFieldsUpdatedAt      CreateHrisTimeoff2QueryParamFields = "updated_at"
	CreateHrisTimeoff2QueryParamFieldsUserID         CreateHrisTimeoff2QueryParamFields = "user_id"
	CreateHrisTimeoff2QueryParamFieldsCompanyID      CreateHrisTimeoff2QueryParamFields = "company_id"
	CreateHrisTimeoff2QueryParamFieldsStartAt        CreateHrisTimeoff2QueryParamFields = "start_at"
	CreateHrisTimeoff2QueryParamFieldsEndAt          CreateHrisTimeoff2QueryParamFields = "end_at"
	CreateHrisTimeoff2QueryParamFieldsIsPaid         CreateHrisTimeoff2QueryParamFields = "is_paid"
	CreateHrisTimeoff2QueryParamFieldsStatus         CreateHrisTimeoff2QueryParamFields = "status"
	CreateHrisTimeoff2QueryParamFieldsApproverUserID CreateHrisTimeoff2QueryParamFields = "approver_user_id"
	CreateHrisTimeoff2QueryParamFieldsApprovedAt     CreateHrisTimeoff2QueryParamFields = "approved_at"
	CreateHrisTimeoff2QueryParamFieldsComments       CreateHrisTimeoff2QueryParamFields = "comments"
	CreateHrisTimeoff2QueryParamFieldsReason         CreateHrisTimeoff2QueryParamFields = "reason"
	CreateHrisTimeoff2QueryParamFieldsType           CreateHrisTimeoff2QueryParamFields = "type"
	CreateHrisTimeoff2QueryParamFieldsDuration       CreateHrisTimeoff2QueryParamFields = "duration"
	CreateHrisTimeoff2QueryParamFieldsDurationType   CreateHrisTimeoff2QueryParamFields = "duration_type"
	CreateHrisTimeoff2QueryParamFieldsRaw            CreateHrisTimeoff2QueryParamFields = "raw"
)

func (e CreateHrisTimeoff2QueryParamFields) ToPointer() *CreateHrisTimeoff2QueryParamFields {
	return &e
}
func (e *CreateHrisTimeoff2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "user_id":
		fallthrough
	case "company_id":
		fallthrough
	case "start_at":
		fallthrough
	case "end_at":
		fallthrough
	case "is_paid":
		fallthrough
	case "status":
		fallthrough
	case "approver_user_id":
		fallthrough
	case "approved_at":
		fallthrough
	case "comments":
		fallthrough
	case "reason":
		fallthrough
	case "type":
		fallthrough
	case "duration":
		fallthrough
	case "duration_type":
		fallthrough
	case "raw":
		*e = CreateHrisTimeoff2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateHrisTimeoff2QueryParamFields: %v", v)
	}
}

type CreateHrisTimeoff2Request struct {
	HrisTimeoff shared.HrisTimeoff `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []CreateHrisTimeoff2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (c *CreateHrisTimeoff2Request) GetHrisTimeoff() shared.HrisTimeoff {
	if c == nil {
		return shared.HrisTimeoff{}
	}
	return c.HrisTimeoff
}

func (c *CreateHrisTimeoff2Request) GetConnectionID() string {
	if c == nil {
		return ""
	}
	return c.ConnectionID
}

func (c *CreateHrisTimeoff2Request) GetFields() []CreateHrisTimeoff2QueryParamFields {
	if c == nil {
		return nil
	}
	return c.Fields
}

func (c *CreateHrisTimeoff2Request) GetRaw() *string {
	if c == nil {
		return nil
	}
	return c.Raw
}

// #region class-body-createhristimeoff2request
// #endregion class-body-createhristimeoff2request

type CreateHrisTimeoff2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	HrisTimeoff *shared.HrisTimeoff
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (c *CreateHrisTimeoff2Response) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateHrisTimeoff2Response) GetHrisTimeoff() *shared.HrisTimeoff {
	if c == nil {
		return nil
	}
	return c.HrisTimeoff
}

func (c *CreateHrisTimeoff2Response) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateHrisTimeoff2Response) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

// #region class-body-createhristimeoff2response
// #endregion class-body-createhristimeoff2response
