// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type GetAccountingOrganization2QueryParamFields string

const (
	GetAccountingOrganization2QueryParamFieldsID                 GetAccountingOrganization2QueryParamFields = "id"
	GetAccountingOrganization2QueryParamFieldsCreatedAt          GetAccountingOrganization2QueryParamFields = "created_at"
	GetAccountingOrganization2QueryParamFieldsUpdatedAt          GetAccountingOrganization2QueryParamFields = "updated_at"
	GetAccountingOrganization2QueryParamFieldsName               GetAccountingOrganization2QueryParamFields = "name"
	GetAccountingOrganization2QueryParamFieldsLegalName          GetAccountingOrganization2QueryParamFields = "legal_name"
	GetAccountingOrganization2QueryParamFieldsCurrency           GetAccountingOrganization2QueryParamFields = "currency"
	GetAccountingOrganization2QueryParamFieldsAddress            GetAccountingOrganization2QueryParamFields = "address"
	GetAccountingOrganization2QueryParamFieldsTaxNumber          GetAccountingOrganization2QueryParamFields = "tax_number"
	GetAccountingOrganization2QueryParamFieldsTimezone           GetAccountingOrganization2QueryParamFields = "timezone"
	GetAccountingOrganization2QueryParamFieldsWebsite            GetAccountingOrganization2QueryParamFields = "website"
	GetAccountingOrganization2QueryParamFieldsParentID           GetAccountingOrganization2QueryParamFields = "parent_id"
	GetAccountingOrganization2QueryParamFieldsFiscalYearEndMonth GetAccountingOrganization2QueryParamFields = "fiscal_year_end_month"
	GetAccountingOrganization2QueryParamFieldsOrganizationCode   GetAccountingOrganization2QueryParamFields = "organization_code"
	GetAccountingOrganization2QueryParamFieldsRaw                GetAccountingOrganization2QueryParamFields = "raw"
)

func (e GetAccountingOrganization2QueryParamFields) ToPointer() *GetAccountingOrganization2QueryParamFields {
	return &e
}
func (e *GetAccountingOrganization2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "legal_name":
		fallthrough
	case "currency":
		fallthrough
	case "address":
		fallthrough
	case "tax_number":
		fallthrough
	case "timezone":
		fallthrough
	case "website":
		fallthrough
	case "parent_id":
		fallthrough
	case "fiscal_year_end_month":
		fallthrough
	case "organization_code":
		fallthrough
	case "raw":
		*e = GetAccountingOrganization2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAccountingOrganization2QueryParamFields: %v", v)
	}
}

type GetAccountingOrganization2Request struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []GetAccountingOrganization2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Organization
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (g *GetAccountingOrganization2Request) GetConnectionID() string {
	if g == nil {
		return ""
	}
	return g.ConnectionID
}

func (g *GetAccountingOrganization2Request) GetFields() []GetAccountingOrganization2QueryParamFields {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetAccountingOrganization2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetAccountingOrganization2Request) GetRaw() *string {
	if g == nil {
		return nil
	}
	return g.Raw
}

// #region class-body-getaccountingorganization2request
// #endregion class-body-getaccountingorganization2request

type GetAccountingOrganization2Response struct {
	// Successful
	AccountingOrganization *shared.AccountingOrganization
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetAccountingOrganization2Response) GetAccountingOrganization() *shared.AccountingOrganization {
	if g == nil {
		return nil
	}
	return g.AccountingOrganization
}

func (g *GetAccountingOrganization2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAccountingOrganization2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAccountingOrganization2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

// #region class-body-getaccountingorganization2response
// #endregion class-body-getaccountingorganization2response
