// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package operations

import (
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type GetCrmPipelineRequest struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Comma-delimited fields to return
	Fields []string `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Pipeline
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetCrmPipelineRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *GetCrmPipelineRequest) GetFields() []string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *GetCrmPipelineRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetCrmPipelineResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	CrmPipeline *shared.CrmPipeline
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetCrmPipelineResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetCrmPipelineResponse) GetCrmPipeline() *shared.CrmPipeline {
	if o == nil {
		return nil
	}
	return o.CrmPipeline
}

func (o *GetCrmPipelineResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetCrmPipelineResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
