// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type GetHrisGroup2QueryParamFields string

const (
	GetHrisGroup2QueryParamFieldsID          GetHrisGroup2QueryParamFields = "id"
	GetHrisGroup2QueryParamFieldsCreatedAt   GetHrisGroup2QueryParamFields = "created_at"
	GetHrisGroup2QueryParamFieldsUpdatedAt   GetHrisGroup2QueryParamFields = "updated_at"
	GetHrisGroup2QueryParamFieldsName        GetHrisGroup2QueryParamFields = "name"
	GetHrisGroup2QueryParamFieldsDescription GetHrisGroup2QueryParamFields = "description"
	GetHrisGroup2QueryParamFieldsParentID    GetHrisGroup2QueryParamFields = "parent_id"
	GetHrisGroup2QueryParamFieldsType        GetHrisGroup2QueryParamFields = "type"
	GetHrisGroup2QueryParamFieldsUserIds     GetHrisGroup2QueryParamFields = "user_ids"
	GetHrisGroup2QueryParamFieldsManagerIds  GetHrisGroup2QueryParamFields = "manager_ids"
	GetHrisGroup2QueryParamFieldsIsActive    GetHrisGroup2QueryParamFields = "is_active"
	GetHrisGroup2QueryParamFieldsCompanyID   GetHrisGroup2QueryParamFields = "company_id"
	GetHrisGroup2QueryParamFieldsRaw         GetHrisGroup2QueryParamFields = "raw"
)

func (e GetHrisGroup2QueryParamFields) ToPointer() *GetHrisGroup2QueryParamFields {
	return &e
}
func (e *GetHrisGroup2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "parent_id":
		fallthrough
	case "type":
		fallthrough
	case "user_ids":
		fallthrough
	case "manager_ids":
		fallthrough
	case "is_active":
		fallthrough
	case "company_id":
		fallthrough
	case "raw":
		*e = GetHrisGroup2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetHrisGroup2QueryParamFields: %v", v)
	}
}

type GetHrisGroup2Request struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []GetHrisGroup2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Group
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (g *GetHrisGroup2Request) GetConnectionID() string {
	if g == nil {
		return ""
	}
	return g.ConnectionID
}

func (g *GetHrisGroup2Request) GetFields() []GetHrisGroup2QueryParamFields {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetHrisGroup2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetHrisGroup2Request) GetRaw() *string {
	if g == nil {
		return nil
	}
	return g.Raw
}

// #region class-body-gethrisgroup2request
// #endregion class-body-gethrisgroup2request

type GetHrisGroup2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	HrisGroup *shared.HrisGroup
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetHrisGroup2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetHrisGroup2Response) GetHrisGroup() *shared.HrisGroup {
	if g == nil {
		return nil
	}
	return g.HrisGroup
}

func (g *GetHrisGroup2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetHrisGroup2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

// #region class-body-gethrisgroup2response
// #endregion class-body-gethrisgroup2response
