// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type GetMartechCampaign2QueryParamFields string

const (
	GetMartechCampaign2QueryParamFieldsID           GetMartechCampaign2QueryParamFields = "id"
	GetMartechCampaign2QueryParamFieldsCreatedAt    GetMartechCampaign2QueryParamFields = "created_at"
	GetMartechCampaign2QueryParamFieldsUpdatedAt    GetMartechCampaign2QueryParamFields = "updated_at"
	GetMartechCampaign2QueryParamFieldsName         GetMartechCampaign2QueryParamFields = "name"
	GetMartechCampaign2QueryParamFieldsType         GetMartechCampaign2QueryParamFields = "type"
	GetMartechCampaign2QueryParamFieldsStatus       GetMartechCampaign2QueryParamFields = "status"
	GetMartechCampaign2QueryParamFieldsListIds      GetMartechCampaign2QueryParamFields = "list_ids"
	GetMartechCampaign2QueryParamFieldsSubjectLine  GetMartechCampaign2QueryParamFields = "subject_line"
	GetMartechCampaign2QueryParamFieldsPreviewText  GetMartechCampaign2QueryParamFields = "preview_text"
	GetMartechCampaign2QueryParamFieldsFromName     GetMartechCampaign2QueryParamFields = "from_name"
	GetMartechCampaign2QueryParamFieldsFromEmail    GetMartechCampaign2QueryParamFields = "from_email"
	GetMartechCampaign2QueryParamFieldsReplyToEmail GetMartechCampaign2QueryParamFields = "reply_to_email"
	GetMartechCampaign2QueryParamFieldsSendAt       GetMartechCampaign2QueryParamFields = "send_at"
	GetMartechCampaign2QueryParamFieldsRaw          GetMartechCampaign2QueryParamFields = "raw"
)

func (e GetMartechCampaign2QueryParamFields) ToPointer() *GetMartechCampaign2QueryParamFields {
	return &e
}
func (e *GetMartechCampaign2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "type":
		fallthrough
	case "status":
		fallthrough
	case "list_ids":
		fallthrough
	case "subject_line":
		fallthrough
	case "preview_text":
		fallthrough
	case "from_name":
		fallthrough
	case "from_email":
		fallthrough
	case "reply_to_email":
		fallthrough
	case "send_at":
		fallthrough
	case "raw":
		*e = GetMartechCampaign2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetMartechCampaign2QueryParamFields: %v", v)
	}
}

type GetMartechCampaign2Request struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []GetMartechCampaign2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Campaign
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (g *GetMartechCampaign2Request) GetConnectionID() string {
	if g == nil {
		return ""
	}
	return g.ConnectionID
}

func (g *GetMartechCampaign2Request) GetFields() []GetMartechCampaign2QueryParamFields {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetMartechCampaign2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetMartechCampaign2Request) GetRaw() *string {
	if g == nil {
		return nil
	}
	return g.Raw
}

// #region class-body-getmartechcampaign2request
// #endregion class-body-getmartechcampaign2request

type GetMartechCampaign2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	MarketingCampaign *shared.MarketingCampaign
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetMartechCampaign2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetMartechCampaign2Response) GetMarketingCampaign() *shared.MarketingCampaign {
	if g == nil {
		return nil
	}
	return g.MarketingCampaign
}

func (g *GetMartechCampaign2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetMartechCampaign2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

// #region class-body-getmartechcampaign2response
// #endregion class-body-getmartechcampaign2response
