// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type GetSigningTemplate2QueryParamFields string

const (
	GetSigningTemplate2QueryParamFieldsID          GetSigningTemplate2QueryParamFields = "id"
	GetSigningTemplate2QueryParamFieldsCreatedAt   GetSigningTemplate2QueryParamFields = "created_at"
	GetSigningTemplate2QueryParamFieldsUpdatedAt   GetSigningTemplate2QueryParamFields = "updated_at"
	GetSigningTemplate2QueryParamFieldsName        GetSigningTemplate2QueryParamFields = "name"
	GetSigningTemplate2QueryParamFieldsDescription GetSigningTemplate2QueryParamFields = "description"
	GetSigningTemplate2QueryParamFieldsIsActive    GetSigningTemplate2QueryParamFields = "is_active"
	GetSigningTemplate2QueryParamFieldsCreatorID   GetSigningTemplate2QueryParamFields = "creator_id"
	GetSigningTemplate2QueryParamFieldsRaw         GetSigningTemplate2QueryParamFields = "raw"
)

func (e GetSigningTemplate2QueryParamFields) ToPointer() *GetSigningTemplate2QueryParamFields {
	return &e
}
func (e *GetSigningTemplate2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "is_active":
		fallthrough
	case "creator_id":
		fallthrough
	case "raw":
		*e = GetSigningTemplate2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetSigningTemplate2QueryParamFields: %v", v)
	}
}

type GetSigningTemplate2Request struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []GetSigningTemplate2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Template
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (g *GetSigningTemplate2Request) GetConnectionID() string {
	if g == nil {
		return ""
	}
	return g.ConnectionID
}

func (g *GetSigningTemplate2Request) GetFields() []GetSigningTemplate2QueryParamFields {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetSigningTemplate2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetSigningTemplate2Request) GetRaw() *string {
	if g == nil {
		return nil
	}
	return g.Raw
}

// #region class-body-getsigningtemplate2request
// #endregion class-body-getsigningtemplate2request

type GetSigningTemplate2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	SigningTemplate *shared.SigningTemplate
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (g *GetSigningTemplate2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetSigningTemplate2Response) GetSigningTemplate() *shared.SigningTemplate {
	if g == nil {
		return nil
	}
	return g.SigningTemplate
}

func (g *GetSigningTemplate2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetSigningTemplate2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

// #region class-body-getsigningtemplate2response
// #endregion class-body-getsigningtemplate2response
