// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type GetStorageFile2QueryParamFields string

const (
	GetStorageFile2QueryParamFieldsID          GetStorageFile2QueryParamFields = "id"
	GetStorageFile2QueryParamFieldsCreatedAt   GetStorageFile2QueryParamFields = "created_at"
	GetStorageFile2QueryParamFieldsUpdatedAt   GetStorageFile2QueryParamFields = "updated_at"
	GetStorageFile2QueryParamFieldsName        GetStorageFile2QueryParamFields = "name"
	GetStorageFile2QueryParamFieldsDescription GetStorageFile2QueryParamFields = "description"
	GetStorageFile2QueryParamFieldsParentID    GetStorageFile2QueryParamFields = "parent_id"
	GetStorageFile2QueryParamFieldsUserID      GetStorageFile2QueryParamFields = "user_id"
	GetStorageFile2QueryParamFieldsSize        GetStorageFile2QueryParamFields = "size"
	GetStorageFile2QueryParamFieldsType        GetStorageFile2QueryParamFields = "type"
	GetStorageFile2QueryParamFieldsMimeType    GetStorageFile2QueryParamFields = "mime_type"
	GetStorageFile2QueryParamFieldsPermissions GetStorageFile2QueryParamFields = "permissions"
	GetStorageFile2QueryParamFieldsDownloadURL GetStorageFile2QueryParamFields = "download_url"
	GetStorageFile2QueryParamFieldsHash        GetStorageFile2QueryParamFields = "hash"
	GetStorageFile2QueryParamFieldsData        GetStorageFile2QueryParamFields = "data"
	GetStorageFile2QueryParamFieldsVersion     GetStorageFile2QueryParamFields = "version"
	GetStorageFile2QueryParamFieldsWebURL      GetStorageFile2QueryParamFields = "web_url"
	GetStorageFile2QueryParamFieldsReferences  GetStorageFile2QueryParamFields = "references"
	GetStorageFile2QueryParamFieldsRaw         GetStorageFile2QueryParamFields = "raw"
)

func (e GetStorageFile2QueryParamFields) ToPointer() *GetStorageFile2QueryParamFields {
	return &e
}
func (e *GetStorageFile2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "parent_id":
		fallthrough
	case "user_id":
		fallthrough
	case "size":
		fallthrough
	case "type":
		fallthrough
	case "mime_type":
		fallthrough
	case "permissions":
		fallthrough
	case "download_url":
		fallthrough
	case "hash":
		fallthrough
	case "data":
		fallthrough
	case "version":
		fallthrough
	case "web_url":
		fallthrough
	case "references":
		fallthrough
	case "raw":
		*e = GetStorageFile2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetStorageFile2QueryParamFields: %v", v)
	}
}

type GetStorageFile2Request struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []GetStorageFile2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the File
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (g *GetStorageFile2Request) GetConnectionID() string {
	if g == nil {
		return ""
	}
	return g.ConnectionID
}

func (g *GetStorageFile2Request) GetFields() []GetStorageFile2QueryParamFields {
	if g == nil {
		return nil
	}
	return g.Fields
}

func (g *GetStorageFile2Request) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetStorageFile2Request) GetRaw() *string {
	if g == nil {
		return nil
	}
	return g.Raw
}

// #region class-body-getstoragefile2request
// #endregion class-body-getstoragefile2request

type GetStorageFile2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful
	StorageFile *shared.StorageFile
}

func (g *GetStorageFile2Response) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetStorageFile2Response) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetStorageFile2Response) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetStorageFile2Response) GetStorageFile() *shared.StorageFile {
	if g == nil {
		return nil
	}
	return g.StorageFile
}

// #region class-body-getstoragefile2response
// #endregion class-body-getstoragefile2response
