// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"net/http"
	"time"
)

type GetTicketingConnectionIDTicketRequest struct {
	// The agent ID to filter results
	AgentID *string `queryParam:"style=form,explode=true,name=agent_id"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// The customer ID to filter results
	CustomerID *string  `queryParam:"style=form,explode=true,name=customer_id"`
	Limit      *float64 `queryParam:"style=form,explode=true,name=limit"`
	Offset     *float64 `queryParam:"style=form,explode=true,name=offset"`
	Order      *string  `queryParam:"style=form,explode=true,name=order"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	Sort  *string `queryParam:"style=form,explode=true,name=sort"`
	// Return only results whose updated date is equal or greater to this value
	UpdatedGte *time.Time `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (g GetTicketingConnectionIDTicketRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTicketingConnectionIDTicketRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetTicketingConnectionIDTicketRequest) GetAgentID() *string {
	if o == nil {
		return nil
	}
	return o.AgentID
}

func (o *GetTicketingConnectionIDTicketRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *GetTicketingConnectionIDTicketRequest) GetCustomerID() *string {
	if o == nil {
		return nil
	}
	return o.CustomerID
}

func (o *GetTicketingConnectionIDTicketRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *GetTicketingConnectionIDTicketRequest) GetOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *GetTicketingConnectionIDTicketRequest) GetOrder() *string {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *GetTicketingConnectionIDTicketRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *GetTicketingConnectionIDTicketRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *GetTicketingConnectionIDTicketRequest) GetUpdatedGte() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedGte
}

type GetTicketingConnectionIDTicketResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Successful
	TicketingTickets []shared.TicketingTicket
}

func (o *GetTicketingConnectionIDTicketResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetTicketingConnectionIDTicketResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetTicketingConnectionIDTicketResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetTicketingConnectionIDTicketResponse) GetTicketingTickets() []shared.TicketingTicket {
	if o == nil {
		return nil
	}
	return o.TicketingTickets
}
