// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type ListAdsCampaignsQueryParamFields string

const (
	ListAdsCampaignsQueryParamFieldsID                 ListAdsCampaignsQueryParamFields = "id"
	ListAdsCampaignsQueryParamFieldsCreatedAt          ListAdsCampaignsQueryParamFields = "created_at"
	ListAdsCampaignsQueryParamFieldsUpdatedAt          ListAdsCampaignsQueryParamFields = "updated_at"
	ListAdsCampaignsQueryParamFieldsName               ListAdsCampaignsQueryParamFields = "name"
	ListAdsCampaignsQueryParamFieldsOrganizationID     ListAdsCampaignsQueryParamFields = "organization_id"
	ListAdsCampaignsQueryParamFieldsStatus             ListAdsCampaignsQueryParamFields = "status"
	ListAdsCampaignsQueryParamFieldsStartAt            ListAdsCampaignsQueryParamFields = "start_at"
	ListAdsCampaignsQueryParamFieldsEndAt              ListAdsCampaignsQueryParamFields = "end_at"
	ListAdsCampaignsQueryParamFieldsBudgetAmount       ListAdsCampaignsQueryParamFields = "budget_amount"
	ListAdsCampaignsQueryParamFieldsBudgetPeriod       ListAdsCampaignsQueryParamFields = "budget_period"
	ListAdsCampaignsQueryParamFieldsCurrency           ListAdsCampaignsQueryParamFields = "currency"
	ListAdsCampaignsQueryParamFieldsTotalSpendAmount   ListAdsCampaignsQueryParamFields = "total_spend_amount"
	ListAdsCampaignsQueryParamFieldsTargeting          ListAdsCampaignsQueryParamFields = "targeting"
	ListAdsCampaignsQueryParamFieldsRaw                ListAdsCampaignsQueryParamFields = "raw"
	ListAdsCampaignsQueryParamFieldsGoal               ListAdsCampaignsQueryParamFields = "goal"
	ListAdsCampaignsQueryParamFieldsPlannedSpendAmount ListAdsCampaignsQueryParamFields = "planned_spend_amount"
	ListAdsCampaignsQueryParamFieldsFrequencyCap       ListAdsCampaignsQueryParamFields = "frequency_cap"
	ListAdsCampaignsQueryParamFieldsIsActive           ListAdsCampaignsQueryParamFields = "is_active"
)

func (e ListAdsCampaignsQueryParamFields) ToPointer() *ListAdsCampaignsQueryParamFields {
	return &e
}
func (e *ListAdsCampaignsQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "organization_id":
		fallthrough
	case "status":
		fallthrough
	case "start_at":
		fallthrough
	case "end_at":
		fallthrough
	case "budget_amount":
		fallthrough
	case "budget_period":
		fallthrough
	case "currency":
		fallthrough
	case "total_spend_amount":
		fallthrough
	case "targeting":
		fallthrough
	case "raw":
		fallthrough
	case "goal":
		fallthrough
	case "planned_spend_amount":
		fallthrough
	case "frequency_cap":
		fallthrough
	case "is_active":
		*e = ListAdsCampaignsQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAdsCampaignsQueryParamFields: %v", v)
	}
}

type ListAdsCampaignsRequest struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []ListAdsCampaignsQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	Limit  *float64                           `queryParam:"style=form,explode=true,name=limit"`
	Offset *float64                           `queryParam:"style=form,explode=true,name=offset"`
	Order  *string                            `queryParam:"style=form,explode=true,name=order"`
	// The org ID to filter by (reference to AdsOrganization)
	OrgID *string `queryParam:"style=form,explode=true,name=org_id"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw  *string `queryParam:"style=form,explode=true,name=raw"`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	UpdatedGte *string `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l *ListAdsCampaignsRequest) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListAdsCampaignsRequest) GetFields() []ListAdsCampaignsQueryParamFields {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListAdsCampaignsRequest) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAdsCampaignsRequest) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListAdsCampaignsRequest) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListAdsCampaignsRequest) GetOrgID() *string {
	if l == nil {
		return nil
	}
	return l.OrgID
}

func (l *ListAdsCampaignsRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListAdsCampaignsRequest) GetRaw() *string {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *ListAdsCampaignsRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListAdsCampaignsRequest) GetUpdatedGte() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedGte
}

type ListAdsCampaignsResponse struct {
	// Successful
	AdsCampaigns []shared.AdsCampaign
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListAdsCampaignsResponse) GetAdsCampaigns() []shared.AdsCampaign {
	if l == nil {
		return nil
	}
	return l.AdsCampaigns
}

func (l *ListAdsCampaignsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListAdsCampaignsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListAdsCampaignsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
