// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type ListCommerceCollections2QueryParamFields string

const (
	ListCommerceCollections2QueryParamFieldsID                ListCommerceCollections2QueryParamFields = "id"
	ListCommerceCollections2QueryParamFieldsCreatedAt         ListCommerceCollections2QueryParamFields = "created_at"
	ListCommerceCollections2QueryParamFieldsUpdatedAt         ListCommerceCollections2QueryParamFields = "updated_at"
	ListCommerceCollections2QueryParamFieldsName              ListCommerceCollections2QueryParamFields = "name"
	ListCommerceCollections2QueryParamFieldsPublicName        ListCommerceCollections2QueryParamFields = "public_name"
	ListCommerceCollections2QueryParamFieldsDescription       ListCommerceCollections2QueryParamFields = "description"
	ListCommerceCollections2QueryParamFieldsPublicDescription ListCommerceCollections2QueryParamFields = "public_description"
	ListCommerceCollections2QueryParamFieldsMedia             ListCommerceCollections2QueryParamFields = "media"
	ListCommerceCollections2QueryParamFieldsIsVisible         ListCommerceCollections2QueryParamFields = "is_visible"
	ListCommerceCollections2QueryParamFieldsIsActive          ListCommerceCollections2QueryParamFields = "is_active"
	ListCommerceCollections2QueryParamFieldsIsFeatured        ListCommerceCollections2QueryParamFields = "is_featured"
	ListCommerceCollections2QueryParamFieldsTags              ListCommerceCollections2QueryParamFields = "tags"
	ListCommerceCollections2QueryParamFieldsType              ListCommerceCollections2QueryParamFields = "type"
	ListCommerceCollections2QueryParamFieldsParentID          ListCommerceCollections2QueryParamFields = "parent_id"
	ListCommerceCollections2QueryParamFieldsMetadata          ListCommerceCollections2QueryParamFields = "metadata"
	ListCommerceCollections2QueryParamFieldsItemMetadata      ListCommerceCollections2QueryParamFields = "item_metadata"
	ListCommerceCollections2QueryParamFieldsRaw               ListCommerceCollections2QueryParamFields = "raw"
)

func (e ListCommerceCollections2QueryParamFields) ToPointer() *ListCommerceCollections2QueryParamFields {
	return &e
}
func (e *ListCommerceCollections2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "public_name":
		fallthrough
	case "description":
		fallthrough
	case "public_description":
		fallthrough
	case "media":
		fallthrough
	case "is_visible":
		fallthrough
	case "is_active":
		fallthrough
	case "is_featured":
		fallthrough
	case "tags":
		fallthrough
	case "type":
		fallthrough
	case "parent_id":
		fallthrough
	case "metadata":
		fallthrough
	case "item_metadata":
		fallthrough
	case "raw":
		*e = ListCommerceCollections2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListCommerceCollections2QueryParamFields: %v", v)
	}
}

type ListCommerceCollections2Request struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []ListCommerceCollections2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	Limit  *float64                                   `queryParam:"style=form,explode=true,name=limit"`
	Offset *float64                                   `queryParam:"style=form,explode=true,name=offset"`
	Order  *string                                    `queryParam:"style=form,explode=true,name=order"`
	// The org ID to filter by (reference to AccountingOrganization)
	OrgID *string `queryParam:"style=form,explode=true,name=org_id"`
	// The parent ID to filter by
	ParentID *string `queryParam:"style=form,explode=true,name=parent_id"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
	// The saleschannel ID to filter by (reference to CommerceSaleschannel)
	SaleschannelID *string `queryParam:"style=form,explode=true,name=saleschannel_id"`
	Sort           *string `queryParam:"style=form,explode=true,name=sort"`
	Type           *string `queryParam:"style=form,explode=true,name=type"`
	// Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	UpdatedGte *string `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l *ListCommerceCollections2Request) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListCommerceCollections2Request) GetFields() []ListCommerceCollections2QueryParamFields {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListCommerceCollections2Request) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListCommerceCollections2Request) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListCommerceCollections2Request) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListCommerceCollections2Request) GetOrgID() *string {
	if l == nil {
		return nil
	}
	return l.OrgID
}

func (l *ListCommerceCollections2Request) GetParentID() *string {
	if l == nil {
		return nil
	}
	return l.ParentID
}

func (l *ListCommerceCollections2Request) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListCommerceCollections2Request) GetRaw() *string {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *ListCommerceCollections2Request) GetSaleschannelID() *string {
	if l == nil {
		return nil
	}
	return l.SaleschannelID
}

func (l *ListCommerceCollections2Request) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListCommerceCollections2Request) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *ListCommerceCollections2Request) GetUpdatedGte() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedGte
}

// #region class-body-listcommercecollections2request
// #endregion class-body-listcommercecollections2request

type ListCommerceCollections2Response struct {
	// Successful
	CommerceCollections []shared.CommerceCollection
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListCommerceCollections2Response) GetCommerceCollections() []shared.CommerceCollection {
	if l == nil {
		return nil
	}
	return l.CommerceCollections
}

func (l *ListCommerceCollections2Response) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListCommerceCollections2Response) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListCommerceCollections2Response) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

// #region class-body-listcommercecollections2response
// #endregion class-body-listcommercecollections2response
