// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"net/http"
	"time"
)

type ListKmsPagesRequest struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Comma-delimited fields to return
	Fields   []string `queryParam:"style=form,explode=true,name=fields"`
	Limit    *float64 `queryParam:"style=form,explode=true,name=limit"`
	Offset   *float64 `queryParam:"style=form,explode=true,name=offset"`
	Order    *string  `queryParam:"style=form,explode=true,name=order"`
	ParentID *string  `queryParam:"style=form,explode=true,name=parent_id"`
	// Query string to search. eg. email address or name
	Query   *string `queryParam:"style=form,explode=true,name=query"`
	Sort    *string `queryParam:"style=form,explode=true,name=sort"`
	SpaceID *string `queryParam:"style=form,explode=true,name=space_id"`
	// Return only results whose updated date is equal or greater to this value
	UpdatedGte *time.Time `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l ListKmsPagesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListKmsPagesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListKmsPagesRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *ListKmsPagesRequest) GetFields() []string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *ListKmsPagesRequest) GetLimit() *float64 {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListKmsPagesRequest) GetOffset() *float64 {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListKmsPagesRequest) GetOrder() *string {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *ListKmsPagesRequest) GetParentID() *string {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *ListKmsPagesRequest) GetQuery() *string {
	if o == nil {
		return nil
	}
	return o.Query
}

func (o *ListKmsPagesRequest) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *ListKmsPagesRequest) GetSpaceID() *string {
	if o == nil {
		return nil
	}
	return o.SpaceID
}

func (o *ListKmsPagesRequest) GetUpdatedGte() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedGte
}

type ListKmsPagesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	KmsPages []shared.KmsPage
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListKmsPagesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListKmsPagesResponse) GetKmsPages() []shared.KmsPage {
	if o == nil {
		return nil
	}
	return o.KmsPages
}

func (o *ListKmsPagesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListKmsPagesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
