// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type ListPaymentLinksQueryParamFields string

const (
	ListPaymentLinksQueryParamFieldsID              ListPaymentLinksQueryParamFields = "id"
	ListPaymentLinksQueryParamFieldsCreatedAt       ListPaymentLinksQueryParamFields = "created_at"
	ListPaymentLinksQueryParamFieldsUpdatedAt       ListPaymentLinksQueryParamFields = "updated_at"
	ListPaymentLinksQueryParamFieldsIsActive        ListPaymentLinksQueryParamFields = "is_active"
	ListPaymentLinksQueryParamFieldsLineitems       ListPaymentLinksQueryParamFields = "lineitems"
	ListPaymentLinksQueryParamFieldsCurrency        ListPaymentLinksQueryParamFields = "currency"
	ListPaymentLinksQueryParamFieldsAmount          ListPaymentLinksQueryParamFields = "amount"
	ListPaymentLinksQueryParamFieldsPaymentID       ListPaymentLinksQueryParamFields = "payment_id"
	ListPaymentLinksQueryParamFieldsContactID       ListPaymentLinksQueryParamFields = "contact_id"
	ListPaymentLinksQueryParamFieldsURL             ListPaymentLinksQueryParamFields = "url"
	ListPaymentLinksQueryParamFieldsIsChargeableNow ListPaymentLinksQueryParamFields = "is_chargeable_now"
	ListPaymentLinksQueryParamFieldsSuccessURL      ListPaymentLinksQueryParamFields = "success_url"
	ListPaymentLinksQueryParamFieldsRaw             ListPaymentLinksQueryParamFields = "raw"
)

func (e ListPaymentLinksQueryParamFields) ToPointer() *ListPaymentLinksQueryParamFields {
	return &e
}
func (e *ListPaymentLinksQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "is_active":
		fallthrough
	case "lineitems":
		fallthrough
	case "currency":
		fallthrough
	case "amount":
		fallthrough
	case "payment_id":
		fallthrough
	case "contact_id":
		fallthrough
	case "url":
		fallthrough
	case "is_chargeable_now":
		fallthrough
	case "success_url":
		fallthrough
	case "raw":
		*e = ListPaymentLinksQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListPaymentLinksQueryParamFields: %v", v)
	}
}

type ListPaymentLinksRequest struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// The contact ID to filter by (reference to AccountingContact)
	ContactID *string `queryParam:"style=form,explode=true,name=contact_id"`
	// Comma-delimited fields to return
	Fields []ListPaymentLinksQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	Limit  *float64                           `queryParam:"style=form,explode=true,name=limit"`
	Offset *float64                           `queryParam:"style=form,explode=true,name=offset"`
	Order  *string                            `queryParam:"style=form,explode=true,name=order"`
	// The payment ID to filter by (reference to PaymentPayment)
	PaymentID *string `queryParam:"style=form,explode=true,name=payment_id"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw  *string `queryParam:"style=form,explode=true,name=raw"`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	UpdatedGte *string `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l *ListPaymentLinksRequest) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListPaymentLinksRequest) GetContactID() *string {
	if l == nil {
		return nil
	}
	return l.ContactID
}

func (l *ListPaymentLinksRequest) GetFields() []ListPaymentLinksQueryParamFields {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListPaymentLinksRequest) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListPaymentLinksRequest) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListPaymentLinksRequest) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListPaymentLinksRequest) GetPaymentID() *string {
	if l == nil {
		return nil
	}
	return l.PaymentID
}

func (l *ListPaymentLinksRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListPaymentLinksRequest) GetRaw() *string {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *ListPaymentLinksRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListPaymentLinksRequest) GetUpdatedGte() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedGte
}

type ListPaymentLinksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	PaymentLinks []shared.PaymentLink
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListPaymentLinksResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPaymentLinksResponse) GetPaymentLinks() []shared.PaymentLink {
	if l == nil {
		return nil
	}
	return l.PaymentLinks
}

func (l *ListPaymentLinksResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPaymentLinksResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
