// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type ListKmsCommentsQueryParamFields string

const (
	ListKmsCommentsQueryParamFieldsID          ListKmsCommentsQueryParamFields = "id"
	ListKmsCommentsQueryParamFieldsCreatedAt   ListKmsCommentsQueryParamFields = "created_at"
	ListKmsCommentsQueryParamFieldsUpdatedAt   ListKmsCommentsQueryParamFields = "updated_at"
	ListKmsCommentsQueryParamFieldsType        ListKmsCommentsQueryParamFields = "type"
	ListKmsCommentsQueryParamFieldsContentType ListKmsCommentsQueryParamFields = "content_type"
	ListKmsCommentsQueryParamFieldsContent     ListKmsCommentsQueryParamFields = "content"
	ListKmsCommentsQueryParamFieldsUserID      ListKmsCommentsQueryParamFields = "user_id"
	ListKmsCommentsQueryParamFieldsPageID      ListKmsCommentsQueryParamFields = "page_id"
	ListKmsCommentsQueryParamFieldsParentID    ListKmsCommentsQueryParamFields = "parent_id"
	ListKmsCommentsQueryParamFieldsRaw         ListKmsCommentsQueryParamFields = "raw"
)

func (e ListKmsCommentsQueryParamFields) ToPointer() *ListKmsCommentsQueryParamFields {
	return &e
}
func (e *ListKmsCommentsQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "type":
		fallthrough
	case "content_type":
		fallthrough
	case "content":
		fallthrough
	case "user_id":
		fallthrough
	case "page_id":
		fallthrough
	case "parent_id":
		fallthrough
	case "raw":
		*e = ListKmsCommentsQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListKmsCommentsQueryParamFields: %v", v)
	}
}

type ListKmsCommentsRequest struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Comma-delimited fields to return
	Fields []ListKmsCommentsQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	Limit  *float64                          `queryParam:"style=form,explode=true,name=limit"`
	Offset *float64                          `queryParam:"style=form,explode=true,name=offset"`
	Order  *string                           `queryParam:"style=form,explode=true,name=order"`
	// The page ID to filter by (reference to KmsPage)
	PageID *string `queryParam:"style=form,explode=true,name=page_id"`
	// The parent ID to filter by
	ParentID *string `queryParam:"style=form,explode=true,name=parent_id"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw  *string `queryParam:"style=form,explode=true,name=raw"`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// The type to filter by
	Type *string `queryParam:"style=form,explode=true,name=type"`
	// Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	UpdatedGte *string `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l *ListKmsCommentsRequest) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListKmsCommentsRequest) GetFields() []ListKmsCommentsQueryParamFields {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListKmsCommentsRequest) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListKmsCommentsRequest) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListKmsCommentsRequest) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListKmsCommentsRequest) GetPageID() *string {
	if l == nil {
		return nil
	}
	return l.PageID
}

func (l *ListKmsCommentsRequest) GetParentID() *string {
	if l == nil {
		return nil
	}
	return l.ParentID
}

func (l *ListKmsCommentsRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListKmsCommentsRequest) GetRaw() *string {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *ListKmsCommentsRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListKmsCommentsRequest) GetType() *string {
	if l == nil {
		return nil
	}
	return l.Type
}

func (l *ListKmsCommentsRequest) GetUpdatedGte() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedGte
}

type ListKmsCommentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	KmsComments []shared.KmsComment
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListKmsCommentsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListKmsCommentsResponse) GetKmsComments() []shared.KmsComment {
	if l == nil {
		return nil
	}
	return l.KmsComments
}

func (l *ListKmsCommentsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListKmsCommentsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
