// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type ListAdsGroups2QueryParamFields string

const (
	ListAdsGroups2QueryParamFieldsID                   ListAdsGroups2QueryParamFields = "id"
	ListAdsGroups2QueryParamFieldsCreatedAt            ListAdsGroups2QueryParamFields = "created_at"
	ListAdsGroups2QueryParamFieldsUpdatedAt            ListAdsGroups2QueryParamFields = "updated_at"
	ListAdsGroups2QueryParamFieldsName                 ListAdsGroups2QueryParamFields = "name"
	ListAdsGroups2QueryParamFieldsParentID             ListAdsGroups2QueryParamFields = "parent_id"
	ListAdsGroups2QueryParamFieldsCampaignID           ListAdsGroups2QueryParamFields = "campaign_id"
	ListAdsGroups2QueryParamFieldsOrganizationID       ListAdsGroups2QueryParamFields = "organization_id"
	ListAdsGroups2QueryParamFieldsInsertionorderID     ListAdsGroups2QueryParamFields = "insertionorder_id"
	ListAdsGroups2QueryParamFieldsStatus               ListAdsGroups2QueryParamFields = "status"
	ListAdsGroups2QueryParamFieldsTargeting            ListAdsGroups2QueryParamFields = "targeting"
	ListAdsGroups2QueryParamFieldsBidAmount            ListAdsGroups2QueryParamFields = "bid_amount"
	ListAdsGroups2QueryParamFieldsBidStrategy          ListAdsGroups2QueryParamFields = "bid_strategy"
	ListAdsGroups2QueryParamFieldsBudgetAmount         ListAdsGroups2QueryParamFields = "budget_amount"
	ListAdsGroups2QueryParamFieldsBudgetPeriod         ListAdsGroups2QueryParamFields = "budget_period"
	ListAdsGroups2QueryParamFieldsBudgetAllocationType ListAdsGroups2QueryParamFields = "budget_allocation_type"
	ListAdsGroups2QueryParamFieldsStartAt              ListAdsGroups2QueryParamFields = "start_at"
	ListAdsGroups2QueryParamFieldsEndAt                ListAdsGroups2QueryParamFields = "end_at"
	ListAdsGroups2QueryParamFieldsBudgetUnit           ListAdsGroups2QueryParamFields = "budget_unit"
	ListAdsGroups2QueryParamFieldsBudgetMaxAmount      ListAdsGroups2QueryParamFields = "budget_max_amount"
	ListAdsGroups2QueryParamFieldsType                 ListAdsGroups2QueryParamFields = "type"
	ListAdsGroups2QueryParamFieldsHasEuPoliticalAds    ListAdsGroups2QueryParamFields = "has_eu_political_ads"
	ListAdsGroups2QueryParamFieldsPacing               ListAdsGroups2QueryParamFields = "pacing"
	ListAdsGroups2QueryParamFieldsFrequencyCap         ListAdsGroups2QueryParamFields = "frequency_cap"
	ListAdsGroups2QueryParamFieldsCreativeIds          ListAdsGroups2QueryParamFields = "creative_ids"
	ListAdsGroups2QueryParamFieldsOptimizationGoal     ListAdsGroups2QueryParamFields = "optimization_goal"
	ListAdsGroups2QueryParamFieldsBillingEvent         ListAdsGroups2QueryParamFields = "billing_event"
	ListAdsGroups2QueryParamFieldsCurrency             ListAdsGroups2QueryParamFields = "currency"
	ListAdsGroups2QueryParamFieldsPromoted             ListAdsGroups2QueryParamFields = "promoted"
	ListAdsGroups2QueryParamFieldsRaw                  ListAdsGroups2QueryParamFields = "raw"
)

func (e ListAdsGroups2QueryParamFields) ToPointer() *ListAdsGroups2QueryParamFields {
	return &e
}
func (e *ListAdsGroups2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "parent_id":
		fallthrough
	case "campaign_id":
		fallthrough
	case "organization_id":
		fallthrough
	case "insertionorder_id":
		fallthrough
	case "status":
		fallthrough
	case "targeting":
		fallthrough
	case "bid_amount":
		fallthrough
	case "bid_strategy":
		fallthrough
	case "budget_amount":
		fallthrough
	case "budget_period":
		fallthrough
	case "budget_allocation_type":
		fallthrough
	case "start_at":
		fallthrough
	case "end_at":
		fallthrough
	case "budget_unit":
		fallthrough
	case "budget_max_amount":
		fallthrough
	case "type":
		fallthrough
	case "has_eu_political_ads":
		fallthrough
	case "pacing":
		fallthrough
	case "frequency_cap":
		fallthrough
	case "creative_ids":
		fallthrough
	case "optimization_goal":
		fallthrough
	case "billing_event":
		fallthrough
	case "currency":
		fallthrough
	case "promoted":
		fallthrough
	case "raw":
		*e = ListAdsGroups2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListAdsGroups2QueryParamFields: %v", v)
	}
}

type ListAdsGroups2Request struct {
	// The campaign ID to filter by
	CampaignID *string `queryParam:"style=form,explode=true,name=campaign_id"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// The end date to filter by (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	EndLt *string `queryParam:"style=form,explode=true,name=end_lt"`
	// Fields to return
	Fields []ListAdsGroups2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// The IO ID to filter by
	IoID   *string  `queryParam:"style=form,explode=true,name=io_id"`
	Limit  *float64 `queryParam:"style=form,explode=true,name=limit"`
	Offset *float64 `queryParam:"style=form,explode=true,name=offset"`
	Order  *string  `queryParam:"style=form,explode=true,name=order"`
	// The org ID to filter by (reference to AdsOrganization)
	OrgID *string `queryParam:"style=form,explode=true,name=org_id"`
	// The parent ID to filter by
	ParentID *string `queryParam:"style=form,explode=true,name=parent_id"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw  *string `queryParam:"style=form,explode=true,name=raw"`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// The start date to filter by (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	StartGte *string `queryParam:"style=form,explode=true,name=start_gte"`
	// The status to filter by
	Status *string `queryParam:"style=form,explode=true,name=status"`
	// Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	UpdatedGte *string `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l *ListAdsGroups2Request) GetCampaignID() *string {
	if l == nil {
		return nil
	}
	return l.CampaignID
}

func (l *ListAdsGroups2Request) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListAdsGroups2Request) GetEndLt() *string {
	if l == nil {
		return nil
	}
	return l.EndLt
}

func (l *ListAdsGroups2Request) GetFields() []ListAdsGroups2QueryParamFields {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListAdsGroups2Request) GetIoID() *string {
	if l == nil {
		return nil
	}
	return l.IoID
}

func (l *ListAdsGroups2Request) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListAdsGroups2Request) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListAdsGroups2Request) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListAdsGroups2Request) GetOrgID() *string {
	if l == nil {
		return nil
	}
	return l.OrgID
}

func (l *ListAdsGroups2Request) GetParentID() *string {
	if l == nil {
		return nil
	}
	return l.ParentID
}

func (l *ListAdsGroups2Request) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListAdsGroups2Request) GetRaw() *string {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *ListAdsGroups2Request) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListAdsGroups2Request) GetStartGte() *string {
	if l == nil {
		return nil
	}
	return l.StartGte
}

func (l *ListAdsGroups2Request) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListAdsGroups2Request) GetUpdatedGte() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedGte
}

// #region class-body-listadsgroups2request
// #endregion class-body-listadsgroups2request

type ListAdsGroups2Response struct {
	// Successful
	AdsGroups []shared.AdsGroup
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListAdsGroups2Response) GetAdsGroups() []shared.AdsGroup {
	if l == nil {
		return nil
	}
	return l.AdsGroups
}

func (l *ListAdsGroups2Response) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListAdsGroups2Response) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListAdsGroups2Response) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

// #region class-body-listadsgroups2response
// #endregion class-body-listadsgroups2response
