// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type ListLmsContentsQueryParamFields string

const (
	ListLmsContentsQueryParamFieldsID                ListLmsContentsQueryParamFields = "id"
	ListLmsContentsQueryParamFieldsCreatedAt         ListLmsContentsQueryParamFields = "created_at"
	ListLmsContentsQueryParamFieldsUpdatedAt         ListLmsContentsQueryParamFields = "updated_at"
	ListLmsContentsQueryParamFieldsExternalReference ListLmsContentsQueryParamFields = "external_reference"
	ListLmsContentsQueryParamFieldsCourseIds         ListLmsContentsQueryParamFields = "course_ids"
	ListLmsContentsQueryParamFieldsName              ListLmsContentsQueryParamFields = "name"
	ListLmsContentsQueryParamFieldsDescription       ListLmsContentsQueryParamFields = "description"
	ListLmsContentsQueryParamFieldsLanguages         ListLmsContentsQueryParamFields = "languages"
	ListLmsContentsQueryParamFieldsMedia             ListLmsContentsQueryParamFields = "media"
	ListLmsContentsQueryParamFieldsIsActive          ListLmsContentsQueryParamFields = "is_active"
	ListLmsContentsQueryParamFieldsDurationMinutes   ListLmsContentsQueryParamFields = "duration_minutes"
	ListLmsContentsQueryParamFieldsCategories        ListLmsContentsQueryParamFields = "categories"
	ListLmsContentsQueryParamFieldsSkills            ListLmsContentsQueryParamFields = "skills"
	ListLmsContentsQueryParamFieldsSortOrder         ListLmsContentsQueryParamFields = "sort_order"
	ListLmsContentsQueryParamFieldsProviderName      ListLmsContentsQueryParamFields = "provider_name"
	ListLmsContentsQueryParamFieldsShortDescription  ListLmsContentsQueryParamFields = "short_description"
	ListLmsContentsQueryParamFieldsLocalizations     ListLmsContentsQueryParamFields = "localizations"
	ListLmsContentsQueryParamFieldsInstructorIds     ListLmsContentsQueryParamFields = "instructor_ids"
	ListLmsContentsQueryParamFieldsCollectionIds     ListLmsContentsQueryParamFields = "collection_ids"
	ListLmsContentsQueryParamFieldsRaw               ListLmsContentsQueryParamFields = "raw"
)

func (e ListLmsContentsQueryParamFields) ToPointer() *ListLmsContentsQueryParamFields {
	return &e
}
func (e *ListLmsContentsQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "external_reference":
		fallthrough
	case "course_ids":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "languages":
		fallthrough
	case "media":
		fallthrough
	case "is_active":
		fallthrough
	case "duration_minutes":
		fallthrough
	case "categories":
		fallthrough
	case "skills":
		fallthrough
	case "sort_order":
		fallthrough
	case "provider_name":
		fallthrough
	case "short_description":
		fallthrough
	case "localizations":
		fallthrough
	case "instructor_ids":
		fallthrough
	case "collection_ids":
		fallthrough
	case "raw":
		*e = ListLmsContentsQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListLmsContentsQueryParamFields: %v", v)
	}
}

type ListLmsContentsRequest struct {
	// The collection ID to filter by (reference to CommerceCollection)
	CollectionID *string `queryParam:"style=form,explode=true,name=collection_id"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// The course ID to filter by (reference to Course)
	CourseID *string `queryParam:"style=form,explode=true,name=course_id"`
	// Fields to return
	Fields []ListLmsContentsQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	Limit  *float64                          `queryParam:"style=form,explode=true,name=limit"`
	Offset *float64                          `queryParam:"style=form,explode=true,name=offset"`
	Order  *string                           `queryParam:"style=form,explode=true,name=order"`
	// Query string to search. eg. email address or name
	Query *string `queryParam:"style=form,explode=true,name=query"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw  *string `queryParam:"style=form,explode=true,name=raw"`
	Sort *string `queryParam:"style=form,explode=true,name=sort"`
	// Return only results whose updated date is equal or greater to this value (ISO-8601 / YYYY-MM-DDTHH:MM:SSZ format)
	UpdatedGte *string `queryParam:"style=form,explode=true,name=updated_gte"`
}

func (l *ListLmsContentsRequest) GetCollectionID() *string {
	if l == nil {
		return nil
	}
	return l.CollectionID
}

func (l *ListLmsContentsRequest) GetConnectionID() string {
	if l == nil {
		return ""
	}
	return l.ConnectionID
}

func (l *ListLmsContentsRequest) GetCourseID() *string {
	if l == nil {
		return nil
	}
	return l.CourseID
}

func (l *ListLmsContentsRequest) GetFields() []ListLmsContentsQueryParamFields {
	if l == nil {
		return nil
	}
	return l.Fields
}

func (l *ListLmsContentsRequest) GetLimit() *float64 {
	if l == nil {
		return nil
	}
	return l.Limit
}

func (l *ListLmsContentsRequest) GetOffset() *float64 {
	if l == nil {
		return nil
	}
	return l.Offset
}

func (l *ListLmsContentsRequest) GetOrder() *string {
	if l == nil {
		return nil
	}
	return l.Order
}

func (l *ListLmsContentsRequest) GetQuery() *string {
	if l == nil {
		return nil
	}
	return l.Query
}

func (l *ListLmsContentsRequest) GetRaw() *string {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *ListLmsContentsRequest) GetSort() *string {
	if l == nil {
		return nil
	}
	return l.Sort
}

func (l *ListLmsContentsRequest) GetUpdatedGte() *string {
	if l == nil {
		return nil
	}
	return l.UpdatedGte
}

type ListLmsContentsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	LmsContents []shared.LmsContent
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (l *ListLmsContentsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListLmsContentsResponse) GetLmsContents() []shared.LmsContent {
	if l == nil {
		return nil
	}
	return l.LmsContents
}

func (l *ListLmsContentsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListLmsContentsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}
