// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchFormsForm2QueryParamFields string

const (
	PatchFormsForm2QueryParamFieldsID                      PatchFormsForm2QueryParamFields = "id"
	PatchFormsForm2QueryParamFieldsCreatedAt               PatchFormsForm2QueryParamFields = "created_at"
	PatchFormsForm2QueryParamFieldsUpdatedAt               PatchFormsForm2QueryParamFields = "updated_at"
	PatchFormsForm2QueryParamFieldsName                    PatchFormsForm2QueryParamFields = "name"
	PatchFormsForm2QueryParamFieldsDescription             PatchFormsForm2QueryParamFields = "description"
	PatchFormsForm2QueryParamFieldsFields                  PatchFormsForm2QueryParamFields = "fields"
	PatchFormsForm2QueryParamFieldsIsActive                PatchFormsForm2QueryParamFields = "is_active"
	PatchFormsForm2QueryParamFieldsPublishedURL            PatchFormsForm2QueryParamFields = "published_url"
	PatchFormsForm2QueryParamFieldsResponseCount           PatchFormsForm2QueryParamFields = "response_count"
	PatchFormsForm2QueryParamFieldsHasMultipleSubmissions  PatchFormsForm2QueryParamFields = "has_multiple_submissions"
	PatchFormsForm2QueryParamFieldsHasProgressBar          PatchFormsForm2QueryParamFields = "has_progress_bar"
	PatchFormsForm2QueryParamFieldsHasShuffleQuestions     PatchFormsForm2QueryParamFields = "has_shuffle_questions"
	PatchFormsForm2QueryParamFieldsConfirmationMessage     PatchFormsForm2QueryParamFields = "confirmation_message"
	PatchFormsForm2QueryParamFieldsConfirmationRedirectURL PatchFormsForm2QueryParamFields = "confirmation_redirect_url"
	PatchFormsForm2QueryParamFieldsRaw                     PatchFormsForm2QueryParamFields = "raw"
)

func (e PatchFormsForm2QueryParamFields) ToPointer() *PatchFormsForm2QueryParamFields {
	return &e
}
func (e *PatchFormsForm2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "fields":
		fallthrough
	case "is_active":
		fallthrough
	case "published_url":
		fallthrough
	case "response_count":
		fallthrough
	case "has_multiple_submissions":
		fallthrough
	case "has_progress_bar":
		fallthrough
	case "has_shuffle_questions":
		fallthrough
	case "confirmation_message":
		fallthrough
	case "confirmation_redirect_url":
		fallthrough
	case "raw":
		*e = PatchFormsForm2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchFormsForm2QueryParamFields: %v", v)
	}
}

type PatchFormsForm2Request struct {
	FormsForm shared.FormsForm `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []PatchFormsForm2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Form
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchFormsForm2Request) GetFormsForm() shared.FormsForm {
	if p == nil {
		return shared.FormsForm{}
	}
	return p.FormsForm
}

func (p *PatchFormsForm2Request) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchFormsForm2Request) GetFields() []PatchFormsForm2QueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchFormsForm2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchFormsForm2Request) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

// #region class-body-patchformsform2request
// #endregion class-body-patchformsform2request

type PatchFormsForm2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	FormsForm *shared.FormsForm
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchFormsForm2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchFormsForm2Response) GetFormsForm() *shared.FormsForm {
	if p == nil {
		return nil
	}
	return p.FormsForm
}

func (p *PatchFormsForm2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchFormsForm2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

// #region class-body-patchformsform2response
// #endregion class-body-patchformsform2response
