// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchTicketingCategoryQueryParamFields string

const (
	PatchTicketingCategoryQueryParamFieldsID          PatchTicketingCategoryQueryParamFields = "id"
	PatchTicketingCategoryQueryParamFieldsCreatedAt   PatchTicketingCategoryQueryParamFields = "created_at"
	PatchTicketingCategoryQueryParamFieldsUpdatedAt   PatchTicketingCategoryQueryParamFields = "updated_at"
	PatchTicketingCategoryQueryParamFieldsName        PatchTicketingCategoryQueryParamFields = "name"
	PatchTicketingCategoryQueryParamFieldsDescription PatchTicketingCategoryQueryParamFields = "description"
	PatchTicketingCategoryQueryParamFieldsIsActive    PatchTicketingCategoryQueryParamFields = "is_active"
	PatchTicketingCategoryQueryParamFieldsParentID    PatchTicketingCategoryQueryParamFields = "parent_id"
	PatchTicketingCategoryQueryParamFieldsRaw         PatchTicketingCategoryQueryParamFields = "raw"
)

func (e PatchTicketingCategoryQueryParamFields) ToPointer() *PatchTicketingCategoryQueryParamFields {
	return &e
}
func (e *PatchTicketingCategoryQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "is_active":
		fallthrough
	case "parent_id":
		fallthrough
	case "raw":
		*e = PatchTicketingCategoryQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchTicketingCategoryQueryParamFields: %v", v)
	}
}

type PatchTicketingCategoryRequest struct {
	TicketingCategory shared.TicketingCategory `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Comma-delimited fields to return
	Fields []PatchTicketingCategoryQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Category
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchTicketingCategoryRequest) GetTicketingCategory() shared.TicketingCategory {
	if p == nil {
		return shared.TicketingCategory{}
	}
	return p.TicketingCategory
}

func (p *PatchTicketingCategoryRequest) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchTicketingCategoryRequest) GetFields() []PatchTicketingCategoryQueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchTicketingCategoryRequest) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchTicketingCategoryRequest) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

type PatchTicketingCategoryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful
	TicketingCategory *shared.TicketingCategory
}

func (p *PatchTicketingCategoryResponse) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchTicketingCategoryResponse) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchTicketingCategoryResponse) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

func (p *PatchTicketingCategoryResponse) GetTicketingCategory() *shared.TicketingCategory {
	if p == nil {
		return nil
	}
	return p.TicketingCategory
}
