// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchAccountingPurchaseorder2QueryParamFields string

const (
	PatchAccountingPurchaseorder2QueryParamFieldsID              PatchAccountingPurchaseorder2QueryParamFields = "id"
	PatchAccountingPurchaseorder2QueryParamFieldsCreatedAt       PatchAccountingPurchaseorder2QueryParamFields = "created_at"
	PatchAccountingPurchaseorder2QueryParamFieldsUpdatedAt       PatchAccountingPurchaseorder2QueryParamFields = "updated_at"
	PatchAccountingPurchaseorder2QueryParamFieldsPostedAt        PatchAccountingPurchaseorder2QueryParamFields = "posted_at"
	PatchAccountingPurchaseorder2QueryParamFieldsContactID       PatchAccountingPurchaseorder2QueryParamFields = "contact_id"
	PatchAccountingPurchaseorder2QueryParamFieldsAccountID       PatchAccountingPurchaseorder2QueryParamFields = "account_id"
	PatchAccountingPurchaseorder2QueryParamFieldsCurrency        PatchAccountingPurchaseorder2QueryParamFields = "currency"
	PatchAccountingPurchaseorder2QueryParamFieldsTotalAmount     PatchAccountingPurchaseorder2QueryParamFields = "total_amount"
	PatchAccountingPurchaseorder2QueryParamFieldsShippingAddress PatchAccountingPurchaseorder2QueryParamFields = "shipping_address"
	PatchAccountingPurchaseorder2QueryParamFieldsBillingAddress  PatchAccountingPurchaseorder2QueryParamFields = "billing_address"
	PatchAccountingPurchaseorder2QueryParamFieldsStatus          PatchAccountingPurchaseorder2QueryParamFields = "status"
	PatchAccountingPurchaseorder2QueryParamFieldsLineitems       PatchAccountingPurchaseorder2QueryParamFields = "lineitems"
	PatchAccountingPurchaseorder2QueryParamFieldsOrganizationID  PatchAccountingPurchaseorder2QueryParamFields = "organization_id"
	PatchAccountingPurchaseorder2QueryParamFieldsRaw             PatchAccountingPurchaseorder2QueryParamFields = "raw"
)

func (e PatchAccountingPurchaseorder2QueryParamFields) ToPointer() *PatchAccountingPurchaseorder2QueryParamFields {
	return &e
}
func (e *PatchAccountingPurchaseorder2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "posted_at":
		fallthrough
	case "contact_id":
		fallthrough
	case "account_id":
		fallthrough
	case "currency":
		fallthrough
	case "total_amount":
		fallthrough
	case "shipping_address":
		fallthrough
	case "billing_address":
		fallthrough
	case "status":
		fallthrough
	case "lineitems":
		fallthrough
	case "organization_id":
		fallthrough
	case "raw":
		*e = PatchAccountingPurchaseorder2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchAccountingPurchaseorder2QueryParamFields: %v", v)
	}
}

type PatchAccountingPurchaseorder2Request struct {
	AccountingPurchaseorder shared.AccountingPurchaseorder `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []PatchAccountingPurchaseorder2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Purchaseorder
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchAccountingPurchaseorder2Request) GetAccountingPurchaseorder() shared.AccountingPurchaseorder {
	if p == nil {
		return shared.AccountingPurchaseorder{}
	}
	return p.AccountingPurchaseorder
}

func (p *PatchAccountingPurchaseorder2Request) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchAccountingPurchaseorder2Request) GetFields() []PatchAccountingPurchaseorder2QueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchAccountingPurchaseorder2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchAccountingPurchaseorder2Request) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

// #region class-body-patchaccountingpurchaseorder2request
// #endregion class-body-patchaccountingpurchaseorder2request

type PatchAccountingPurchaseorder2Response struct {
	// Successful
	AccountingPurchaseorder *shared.AccountingPurchaseorder
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchAccountingPurchaseorder2Response) GetAccountingPurchaseorder() *shared.AccountingPurchaseorder {
	if p == nil {
		return nil
	}
	return p.AccountingPurchaseorder
}

func (p *PatchAccountingPurchaseorder2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchAccountingPurchaseorder2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchAccountingPurchaseorder2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

// #region class-body-patchaccountingpurchaseorder2response
// #endregion class-body-patchaccountingpurchaseorder2response
