// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchCommerceItemvariant2QueryParamFields string

const (
	PatchCommerceItemvariant2QueryParamFieldsID                PatchCommerceItemvariant2QueryParamFields = "id"
	PatchCommerceItemvariant2QueryParamFieldsCreatedAt         PatchCommerceItemvariant2QueryParamFields = "created_at"
	PatchCommerceItemvariant2QueryParamFieldsUpdatedAt         PatchCommerceItemvariant2QueryParamFields = "updated_at"
	PatchCommerceItemvariant2QueryParamFieldsName              PatchCommerceItemvariant2QueryParamFields = "name"
	PatchCommerceItemvariant2QueryParamFieldsPublicName        PatchCommerceItemvariant2QueryParamFields = "public_name"
	PatchCommerceItemvariant2QueryParamFieldsDescription       PatchCommerceItemvariant2QueryParamFields = "description"
	PatchCommerceItemvariant2QueryParamFieldsPublicDescription PatchCommerceItemvariant2QueryParamFields = "public_description"
	PatchCommerceItemvariant2QueryParamFieldsSku               PatchCommerceItemvariant2QueryParamFields = "sku"
	PatchCommerceItemvariant2QueryParamFieldsIsActive          PatchCommerceItemvariant2QueryParamFields = "is_active"
	PatchCommerceItemvariant2QueryParamFieldsIsVisible         PatchCommerceItemvariant2QueryParamFields = "is_visible"
	PatchCommerceItemvariant2QueryParamFieldsIsFeatured        PatchCommerceItemvariant2QueryParamFields = "is_featured"
	PatchCommerceItemvariant2QueryParamFieldsMedia             PatchCommerceItemvariant2QueryParamFields = "media"
	PatchCommerceItemvariant2QueryParamFieldsAvailableAt       PatchCommerceItemvariant2QueryParamFields = "available_at"
	PatchCommerceItemvariant2QueryParamFieldsTags              PatchCommerceItemvariant2QueryParamFields = "tags"
	PatchCommerceItemvariant2QueryParamFieldsWidth             PatchCommerceItemvariant2QueryParamFields = "width"
	PatchCommerceItemvariant2QueryParamFieldsHeight            PatchCommerceItemvariant2QueryParamFields = "height"
	PatchCommerceItemvariant2QueryParamFieldsLength            PatchCommerceItemvariant2QueryParamFields = "length"
	PatchCommerceItemvariant2QueryParamFieldsWeight            PatchCommerceItemvariant2QueryParamFields = "weight"
	PatchCommerceItemvariant2QueryParamFieldsSizeUnit          PatchCommerceItemvariant2QueryParamFields = "size_unit"
	PatchCommerceItemvariant2QueryParamFieldsWeightUnit        PatchCommerceItemvariant2QueryParamFields = "weight_unit"
	PatchCommerceItemvariant2QueryParamFieldsTotalStock        PatchCommerceItemvariant2QueryParamFields = "total_stock"
	PatchCommerceItemvariant2QueryParamFieldsPrices            PatchCommerceItemvariant2QueryParamFields = "prices"
	PatchCommerceItemvariant2QueryParamFieldsOptions           PatchCommerceItemvariant2QueryParamFields = "options"
	PatchCommerceItemvariant2QueryParamFieldsInventoryID       PatchCommerceItemvariant2QueryParamFields = "inventory_id"
	PatchCommerceItemvariant2QueryParamFieldsRequiresShipping  PatchCommerceItemvariant2QueryParamFields = "requires_shipping"
	PatchCommerceItemvariant2QueryParamFieldsMetadata          PatchCommerceItemvariant2QueryParamFields = "metadata"
	PatchCommerceItemvariant2QueryParamFieldsItems             PatchCommerceItemvariant2QueryParamFields = "items"
	PatchCommerceItemvariant2QueryParamFieldsRaw               PatchCommerceItemvariant2QueryParamFields = "raw"
)

func (e PatchCommerceItemvariant2QueryParamFields) ToPointer() *PatchCommerceItemvariant2QueryParamFields {
	return &e
}
func (e *PatchCommerceItemvariant2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "public_name":
		fallthrough
	case "description":
		fallthrough
	case "public_description":
		fallthrough
	case "sku":
		fallthrough
	case "is_active":
		fallthrough
	case "is_visible":
		fallthrough
	case "is_featured":
		fallthrough
	case "media":
		fallthrough
	case "available_at":
		fallthrough
	case "tags":
		fallthrough
	case "width":
		fallthrough
	case "height":
		fallthrough
	case "length":
		fallthrough
	case "weight":
		fallthrough
	case "size_unit":
		fallthrough
	case "weight_unit":
		fallthrough
	case "total_stock":
		fallthrough
	case "prices":
		fallthrough
	case "options":
		fallthrough
	case "inventory_id":
		fallthrough
	case "requires_shipping":
		fallthrough
	case "metadata":
		fallthrough
	case "items":
		fallthrough
	case "raw":
		*e = PatchCommerceItemvariant2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchCommerceItemvariant2QueryParamFields: %v", v)
	}
}

type PatchCommerceItemvariant2Request struct {
	CommerceItemvariant shared.CommerceItemvariant `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []PatchCommerceItemvariant2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Itemvariant
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchCommerceItemvariant2Request) GetCommerceItemvariant() shared.CommerceItemvariant {
	if p == nil {
		return shared.CommerceItemvariant{}
	}
	return p.CommerceItemvariant
}

func (p *PatchCommerceItemvariant2Request) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchCommerceItemvariant2Request) GetFields() []PatchCommerceItemvariant2QueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchCommerceItemvariant2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchCommerceItemvariant2Request) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

// #region class-body-patchcommerceitemvariant2request
// #endregion class-body-patchcommerceitemvariant2request

type PatchCommerceItemvariant2Response struct {
	// Successful
	CommerceItemvariant *shared.CommerceItemvariant
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchCommerceItemvariant2Response) GetCommerceItemvariant() *shared.CommerceItemvariant {
	if p == nil {
		return nil
	}
	return p.CommerceItemvariant
}

func (p *PatchCommerceItemvariant2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchCommerceItemvariant2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchCommerceItemvariant2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

// #region class-body-patchcommerceitemvariant2response
// #endregion class-body-patchcommerceitemvariant2response
