// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchDatastoreDatabase2QueryParamFields string

const (
	PatchDatastoreDatabase2QueryParamFieldsID          PatchDatastoreDatabase2QueryParamFields = "id"
	PatchDatastoreDatabase2QueryParamFieldsCreatedAt   PatchDatastoreDatabase2QueryParamFields = "created_at"
	PatchDatastoreDatabase2QueryParamFieldsUpdatedAt   PatchDatastoreDatabase2QueryParamFields = "updated_at"
	PatchDatastoreDatabase2QueryParamFieldsName        PatchDatastoreDatabase2QueryParamFields = "name"
	PatchDatastoreDatabase2QueryParamFieldsDescription PatchDatastoreDatabase2QueryParamFields = "description"
	PatchDatastoreDatabase2QueryParamFieldsWebURL      PatchDatastoreDatabase2QueryParamFields = "web_url"
	PatchDatastoreDatabase2QueryParamFieldsIsActive    PatchDatastoreDatabase2QueryParamFields = "is_active"
	PatchDatastoreDatabase2QueryParamFieldsPassword    PatchDatastoreDatabase2QueryParamFields = "password"
	PatchDatastoreDatabase2QueryParamFieldsRegion      PatchDatastoreDatabase2QueryParamFields = "region"
	PatchDatastoreDatabase2QueryParamFieldsRaw         PatchDatastoreDatabase2QueryParamFields = "raw"
)

func (e PatchDatastoreDatabase2QueryParamFields) ToPointer() *PatchDatastoreDatabase2QueryParamFields {
	return &e
}
func (e *PatchDatastoreDatabase2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "web_url":
		fallthrough
	case "is_active":
		fallthrough
	case "password":
		fallthrough
	case "region":
		fallthrough
	case "raw":
		*e = PatchDatastoreDatabase2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchDatastoreDatabase2QueryParamFields: %v", v)
	}
}

type PatchDatastoreDatabase2Request struct {
	DatastoreDatabase shared.DatastoreDatabase `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []PatchDatastoreDatabase2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Database
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchDatastoreDatabase2Request) GetDatastoreDatabase() shared.DatastoreDatabase {
	if p == nil {
		return shared.DatastoreDatabase{}
	}
	return p.DatastoreDatabase
}

func (p *PatchDatastoreDatabase2Request) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchDatastoreDatabase2Request) GetFields() []PatchDatastoreDatabase2QueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchDatastoreDatabase2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchDatastoreDatabase2Request) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

// #region class-body-patchdatastoredatabase2request
// #endregion class-body-patchdatastoredatabase2request

type PatchDatastoreDatabase2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	DatastoreDatabase *shared.DatastoreDatabase
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchDatastoreDatabase2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchDatastoreDatabase2Response) GetDatastoreDatabase() *shared.DatastoreDatabase {
	if p == nil {
		return nil
	}
	return p.DatastoreDatabase
}

func (p *PatchDatastoreDatabase2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchDatastoreDatabase2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

// #region class-body-patchdatastoredatabase2response
// #endregion class-body-patchdatastoredatabase2response
