// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchDatastoreRecord2QueryParamFields string

const (
	PatchDatastoreRecord2QueryParamFieldsID         PatchDatastoreRecord2QueryParamFields = "id"
	PatchDatastoreRecord2QueryParamFieldsCreatedAt  PatchDatastoreRecord2QueryParamFields = "created_at"
	PatchDatastoreRecord2QueryParamFieldsUpdatedAt  PatchDatastoreRecord2QueryParamFields = "updated_at"
	PatchDatastoreRecord2QueryParamFieldsDatabaseID PatchDatastoreRecord2QueryParamFields = "database_id"
	PatchDatastoreRecord2QueryParamFieldsTableID    PatchDatastoreRecord2QueryParamFields = "table_id"
	PatchDatastoreRecord2QueryParamFieldsFields     PatchDatastoreRecord2QueryParamFields = "fields"
	PatchDatastoreRecord2QueryParamFieldsRowNumber  PatchDatastoreRecord2QueryParamFields = "row_number"
	PatchDatastoreRecord2QueryParamFieldsRaw        PatchDatastoreRecord2QueryParamFields = "raw"
)

func (e PatchDatastoreRecord2QueryParamFields) ToPointer() *PatchDatastoreRecord2QueryParamFields {
	return &e
}
func (e *PatchDatastoreRecord2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "database_id":
		fallthrough
	case "table_id":
		fallthrough
	case "fields":
		fallthrough
	case "row_number":
		fallthrough
	case "raw":
		*e = PatchDatastoreRecord2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchDatastoreRecord2QueryParamFields: %v", v)
	}
}

type PatchDatastoreRecord2Request struct {
	DatastoreRecord shared.DatastoreRecord `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []PatchDatastoreRecord2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Record
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchDatastoreRecord2Request) GetDatastoreRecord() shared.DatastoreRecord {
	if p == nil {
		return shared.DatastoreRecord{}
	}
	return p.DatastoreRecord
}

func (p *PatchDatastoreRecord2Request) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchDatastoreRecord2Request) GetFields() []PatchDatastoreRecord2QueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchDatastoreRecord2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchDatastoreRecord2Request) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

// #region class-body-patchdatastorerecord2request
// #endregion class-body-patchdatastorerecord2request

type PatchDatastoreRecord2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	DatastoreRecord *shared.DatastoreRecord
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchDatastoreRecord2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchDatastoreRecord2Response) GetDatastoreRecord() *shared.DatastoreRecord {
	if p == nil {
		return nil
	}
	return p.DatastoreRecord
}

func (p *PatchDatastoreRecord2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchDatastoreRecord2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

// #region class-body-patchdatastorerecord2response
// #endregion class-body-patchdatastorerecord2response
