// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchSigningDocument2QueryParamFields string

const (
	PatchSigningDocument2QueryParamFieldsID          PatchSigningDocument2QueryParamFields = "id"
	PatchSigningDocument2QueryParamFieldsCreatedAt   PatchSigningDocument2QueryParamFields = "created_at"
	PatchSigningDocument2QueryParamFieldsUpdatedAt   PatchSigningDocument2QueryParamFields = "updated_at"
	PatchSigningDocument2QueryParamFieldsName        PatchSigningDocument2QueryParamFields = "name"
	PatchSigningDocument2QueryParamFieldsDescription PatchSigningDocument2QueryParamFields = "description"
	PatchSigningDocument2QueryParamFieldsStatus      PatchSigningDocument2QueryParamFields = "status"
	PatchSigningDocument2QueryParamFieldsSentAt      PatchSigningDocument2QueryParamFields = "sent_at"
	PatchSigningDocument2QueryParamFieldsCompletedAt PatchSigningDocument2QueryParamFields = "completed_at"
	PatchSigningDocument2QueryParamFieldsExpiresAt   PatchSigningDocument2QueryParamFields = "expires_at"
	PatchSigningDocument2QueryParamFieldsTemplateID  PatchSigningDocument2QueryParamFields = "template_id"
	PatchSigningDocument2QueryParamFieldsDownloadURL PatchSigningDocument2QueryParamFields = "download_url"
	PatchSigningDocument2QueryParamFieldsCreatorID   PatchSigningDocument2QueryParamFields = "creator_id"
	PatchSigningDocument2QueryParamFieldsRaw         PatchSigningDocument2QueryParamFields = "raw"
)

func (e PatchSigningDocument2QueryParamFields) ToPointer() *PatchSigningDocument2QueryParamFields {
	return &e
}
func (e *PatchSigningDocument2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "description":
		fallthrough
	case "status":
		fallthrough
	case "sent_at":
		fallthrough
	case "completed_at":
		fallthrough
	case "expires_at":
		fallthrough
	case "template_id":
		fallthrough
	case "download_url":
		fallthrough
	case "creator_id":
		fallthrough
	case "raw":
		*e = PatchSigningDocument2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PatchSigningDocument2QueryParamFields: %v", v)
	}
}

type PatchSigningDocument2Request struct {
	SigningDocument shared.SigningDocument `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []PatchSigningDocument2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Document
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (p *PatchSigningDocument2Request) GetSigningDocument() shared.SigningDocument {
	if p == nil {
		return shared.SigningDocument{}
	}
	return p.SigningDocument
}

func (p *PatchSigningDocument2Request) GetConnectionID() string {
	if p == nil {
		return ""
	}
	return p.ConnectionID
}

func (p *PatchSigningDocument2Request) GetFields() []PatchSigningDocument2QueryParamFields {
	if p == nil {
		return nil
	}
	return p.Fields
}

func (p *PatchSigningDocument2Request) GetID() string {
	if p == nil {
		return ""
	}
	return p.ID
}

func (p *PatchSigningDocument2Request) GetRaw() *string {
	if p == nil {
		return nil
	}
	return p.Raw
}

// #region class-body-patchsigningdocument2request
// #endregion class-body-patchsigningdocument2request

type PatchSigningDocument2Response struct {
	// HTTP response content type for this operation
	ContentType string
	// Successful
	SigningDocument *shared.SigningDocument
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (p *PatchSigningDocument2Response) GetContentType() string {
	if p == nil {
		return ""
	}
	return p.ContentType
}

func (p *PatchSigningDocument2Response) GetSigningDocument() *shared.SigningDocument {
	if p == nil {
		return nil
	}
	return p.SigningDocument
}

func (p *PatchSigningDocument2Response) GetStatusCode() int {
	if p == nil {
		return 0
	}
	return p.StatusCode
}

func (p *PatchSigningDocument2Response) GetRawResponse() *http.Response {
	if p == nil {
		return nil
	}
	return p.RawResponse
}

// #region class-body-patchsigningdocument2response
// #endregion class-body-patchsigningdocument2response
