// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type PatchCalendarLinkRequest struct {
	CalendarLink shared.CalendarLink `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Comma-delimited fields to return
	Fields []string `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Link
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (o *PatchCalendarLinkRequest) GetCalendarLink() shared.CalendarLink {
	if o == nil {
		return shared.CalendarLink{}
	}
	return o.CalendarLink
}

func (o *PatchCalendarLinkRequest) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *PatchCalendarLinkRequest) GetFields() []string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *PatchCalendarLinkRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PatchCalendarLinkRequest) GetRaw() *string {
	if o == nil {
		return nil
	}
	return o.Raw
}

type PatchCalendarLinkResponse struct {
	// Successful
	CalendarLink *shared.CalendarLink
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchCalendarLinkResponse) GetCalendarLink() *shared.CalendarLink {
	if o == nil {
		return nil
	}
	return o.CalendarLink
}

func (o *PatchCalendarLinkResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchCalendarLinkResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchCalendarLinkResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
