// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type RemoveAccountingQuoteRequest struct {
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// ID of the Quote
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (r *RemoveAccountingQuoteRequest) GetConnectionID() string {
	if r == nil {
		return ""
	}
	return r.ConnectionID
}

func (r *RemoveAccountingQuoteRequest) GetID() string {
	if r == nil {
		return ""
	}
	return r.ID
}

type RemoveAccountingQuoteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (r *RemoveAccountingQuoteResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RemoveAccountingQuoteResponse) GetHeaders() map[string][]string {
	if r == nil {
		return map[string][]string{}
	}
	return r.Headers
}

func (r *RemoveAccountingQuoteResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RemoveAccountingQuoteResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}
