// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type UpdateAtsCandidate2QueryParamFields string

const (
	UpdateAtsCandidate2QueryParamFieldsID                 UpdateAtsCandidate2QueryParamFields = "id"
	UpdateAtsCandidate2QueryParamFieldsCreatedAt          UpdateAtsCandidate2QueryParamFields = "created_at"
	UpdateAtsCandidate2QueryParamFieldsUpdatedAt          UpdateAtsCandidate2QueryParamFields = "updated_at"
	UpdateAtsCandidate2QueryParamFieldsName               UpdateAtsCandidate2QueryParamFields = "name"
	UpdateAtsCandidate2QueryParamFieldsFirstName          UpdateAtsCandidate2QueryParamFields = "first_name"
	UpdateAtsCandidate2QueryParamFieldsLastName           UpdateAtsCandidate2QueryParamFields = "last_name"
	UpdateAtsCandidate2QueryParamFieldsEmails             UpdateAtsCandidate2QueryParamFields = "emails"
	UpdateAtsCandidate2QueryParamFieldsTitle              UpdateAtsCandidate2QueryParamFields = "title"
	UpdateAtsCandidate2QueryParamFieldsTelephones         UpdateAtsCandidate2QueryParamFields = "telephones"
	UpdateAtsCandidate2QueryParamFieldsCompanyName        UpdateAtsCandidate2QueryParamFields = "company_name"
	UpdateAtsCandidate2QueryParamFieldsImageURL           UpdateAtsCandidate2QueryParamFields = "image_url"
	UpdateAtsCandidate2QueryParamFieldsTags               UpdateAtsCandidate2QueryParamFields = "tags"
	UpdateAtsCandidate2QueryParamFieldsAddress            UpdateAtsCandidate2QueryParamFields = "address"
	UpdateAtsCandidate2QueryParamFieldsExternalIdentifier UpdateAtsCandidate2QueryParamFields = "external_identifier"
	UpdateAtsCandidate2QueryParamFieldsLinkUrls           UpdateAtsCandidate2QueryParamFields = "link_urls"
	UpdateAtsCandidate2QueryParamFieldsOrigin             UpdateAtsCandidate2QueryParamFields = "origin"
	UpdateAtsCandidate2QueryParamFieldsCompanyID          UpdateAtsCandidate2QueryParamFields = "company_id"
	UpdateAtsCandidate2QueryParamFieldsSources            UpdateAtsCandidate2QueryParamFields = "sources"
	UpdateAtsCandidate2QueryParamFieldsDateOfBirth        UpdateAtsCandidate2QueryParamFields = "date_of_birth"
	UpdateAtsCandidate2QueryParamFieldsUserID             UpdateAtsCandidate2QueryParamFields = "user_id"
	UpdateAtsCandidate2QueryParamFieldsWebURL             UpdateAtsCandidate2QueryParamFields = "web_url"
	UpdateAtsCandidate2QueryParamFieldsExperiences        UpdateAtsCandidate2QueryParamFields = "experiences"
	UpdateAtsCandidate2QueryParamFieldsEducation          UpdateAtsCandidate2QueryParamFields = "education"
	UpdateAtsCandidate2QueryParamFieldsSkills             UpdateAtsCandidate2QueryParamFields = "skills"
	UpdateAtsCandidate2QueryParamFieldsJobIds             UpdateAtsCandidate2QueryParamFields = "job_ids"
	UpdateAtsCandidate2QueryParamFieldsMetadata           UpdateAtsCandidate2QueryParamFields = "metadata"
	UpdateAtsCandidate2QueryParamFieldsRaw                UpdateAtsCandidate2QueryParamFields = "raw"
)

func (e UpdateAtsCandidate2QueryParamFields) ToPointer() *UpdateAtsCandidate2QueryParamFields {
	return &e
}
func (e *UpdateAtsCandidate2QueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "first_name":
		fallthrough
	case "last_name":
		fallthrough
	case "emails":
		fallthrough
	case "title":
		fallthrough
	case "telephones":
		fallthrough
	case "company_name":
		fallthrough
	case "image_url":
		fallthrough
	case "tags":
		fallthrough
	case "address":
		fallthrough
	case "external_identifier":
		fallthrough
	case "link_urls":
		fallthrough
	case "origin":
		fallthrough
	case "company_id":
		fallthrough
	case "sources":
		fallthrough
	case "date_of_birth":
		fallthrough
	case "user_id":
		fallthrough
	case "web_url":
		fallthrough
	case "experiences":
		fallthrough
	case "education":
		fallthrough
	case "skills":
		fallthrough
	case "job_ids":
		fallthrough
	case "metadata":
		fallthrough
	case "raw":
		*e = UpdateAtsCandidate2QueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateAtsCandidate2QueryParamFields: %v", v)
	}
}

type UpdateAtsCandidate2Request struct {
	AtsCandidate shared.AtsCandidate `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []UpdateAtsCandidate2QueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Candidate
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (u *UpdateAtsCandidate2Request) GetAtsCandidate() shared.AtsCandidate {
	if u == nil {
		return shared.AtsCandidate{}
	}
	return u.AtsCandidate
}

func (u *UpdateAtsCandidate2Request) GetConnectionID() string {
	if u == nil {
		return ""
	}
	return u.ConnectionID
}

func (u *UpdateAtsCandidate2Request) GetFields() []UpdateAtsCandidate2QueryParamFields {
	if u == nil {
		return nil
	}
	return u.Fields
}

func (u *UpdateAtsCandidate2Request) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateAtsCandidate2Request) GetRaw() *string {
	if u == nil {
		return nil
	}
	return u.Raw
}

// #region class-body-updateatscandidate2request
// #endregion class-body-updateatscandidate2request

type UpdateAtsCandidate2Response struct {
	// Successful
	AtsCandidate *shared.AtsCandidate
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (u *UpdateAtsCandidate2Response) GetAtsCandidate() *shared.AtsCandidate {
	if u == nil {
		return nil
	}
	return u.AtsCandidate
}

func (u *UpdateAtsCandidate2Response) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAtsCandidate2Response) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAtsCandidate2Response) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

// #region class-body-updateatscandidate2response
// #endregion class-body-updateatscandidate2response
