// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/models/shared"
	"net/http"
)

type UpdateUcContactQueryParamFields string

const (
	UpdateUcContactQueryParamFieldsID         UpdateUcContactQueryParamFields = "id"
	UpdateUcContactQueryParamFieldsCreatedAt  UpdateUcContactQueryParamFields = "created_at"
	UpdateUcContactQueryParamFieldsUpdatedAt  UpdateUcContactQueryParamFields = "updated_at"
	UpdateUcContactQueryParamFieldsName       UpdateUcContactQueryParamFields = "name"
	UpdateUcContactQueryParamFieldsFirstName  UpdateUcContactQueryParamFields = "first_name"
	UpdateUcContactQueryParamFieldsLastName   UpdateUcContactQueryParamFields = "last_name"
	UpdateUcContactQueryParamFieldsTitle      UpdateUcContactQueryParamFields = "title"
	UpdateUcContactQueryParamFieldsCompany    UpdateUcContactQueryParamFields = "company"
	UpdateUcContactQueryParamFieldsEmails     UpdateUcContactQueryParamFields = "emails"
	UpdateUcContactQueryParamFieldsTelephones UpdateUcContactQueryParamFields = "telephones"
	UpdateUcContactQueryParamFieldsRaw        UpdateUcContactQueryParamFields = "raw"
)

func (e UpdateUcContactQueryParamFields) ToPointer() *UpdateUcContactQueryParamFields {
	return &e
}
func (e *UpdateUcContactQueryParamFields) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		fallthrough
	case "updated_at":
		fallthrough
	case "name":
		fallthrough
	case "first_name":
		fallthrough
	case "last_name":
		fallthrough
	case "title":
		fallthrough
	case "company":
		fallthrough
	case "emails":
		fallthrough
	case "telephones":
		fallthrough
	case "raw":
		*e = UpdateUcContactQueryParamFields(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateUcContactQueryParamFields: %v", v)
	}
}

type UpdateUcContactRequest struct {
	// A contact represents a person that optionally is associated with a call
	UcContact shared.UcContact `request:"mediaType=application/json"`
	// ID of the connection
	ConnectionID string `pathParam:"style=simple,explode=false,name=connection_id"`
	// Fields to return
	Fields []UpdateUcContactQueryParamFields `queryParam:"style=form,explode=true,name=fields"`
	// ID of the Contact
	ID string `pathParam:"style=simple,explode=false,name=id"`
	// Raw parameters to include in the 3rd-party request. Encoded as a URL component. eg. raw parameters: foo=bar&zoo=bar -> raw=foo%3Dbar%26zoo%3Dbar
	Raw *string `queryParam:"style=form,explode=true,name=raw"`
}

func (u *UpdateUcContactRequest) GetUcContact() shared.UcContact {
	if u == nil {
		return shared.UcContact{}
	}
	return u.UcContact
}

func (u *UpdateUcContactRequest) GetConnectionID() string {
	if u == nil {
		return ""
	}
	return u.ConnectionID
}

func (u *UpdateUcContactRequest) GetFields() []UpdateUcContactQueryParamFields {
	if u == nil {
		return nil
	}
	return u.Fields
}

func (u *UpdateUcContactRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateUcContactRequest) GetRaw() *string {
	if u == nil {
		return nil
	}
	return u.Raw
}

type UpdateUcContactResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful
	UcContact *shared.UcContact
}

func (u *UpdateUcContactResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateUcContactResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateUcContactResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateUcContactResponse) GetUcContact() *shared.UcContact {
	if u == nil {
		return nil
	}
	return u.UcContact
}
