// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

type AccountingAgedRow struct {
	BalanceAmount *float64                              `json:"balance_amount,omitempty"`
	Contact       *PropertyAccountingAgedRowContact     `json:"contact,omitempty"`
	DueAt         *time.Time                            `json:"due_at,omitempty"`
	PostedAt      *time.Time                            `json:"posted_at,omitempty"`
	TotalAmount   *float64                              `json:"total_amount,omitempty"`
	Transaction   *PropertyAccountingAgedRowTransaction `json:"transaction,omitempty"`
}

func (a AccountingAgedRow) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AccountingAgedRow) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AccountingAgedRow) GetBalanceAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.BalanceAmount
}

func (a *AccountingAgedRow) GetContact() *PropertyAccountingAgedRowContact {
	if a == nil {
		return nil
	}
	return a.Contact
}

func (a *AccountingAgedRow) GetDueAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.DueAt
}

func (a *AccountingAgedRow) GetPostedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.PostedAt
}

func (a *AccountingAgedRow) GetTotalAmount() *float64 {
	if a == nil {
		return nil
	}
	return a.TotalAmount
}

func (a *AccountingAgedRow) GetTransaction() *PropertyAccountingAgedRowTransaction {
	if a == nil {
		return nil
	}
	return a.Transaction
}
