// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AccountingProfitlossSubcategory - @deprecated
type AccountingProfitlossSubcategory struct {
	Amount         *float64 `json:"amount,omitempty"`
	Name           *string  `json:"name,omitempty"`
	TransactionIds []string `json:"transaction_ids,omitempty"`
}

func (o *AccountingProfitlossSubcategory) GetAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.Amount
}

func (o *AccountingProfitlossSubcategory) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *AccountingProfitlossSubcategory) GetTransactionIds() []string {
	if o == nil {
		return nil
	}
	return o.TransactionIds
}
