// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

type AnalyticsSession struct {
	Browser         *string        `json:"browser,omitempty"`
	Campaign        *string        `json:"campaign,omitempty"`
	City            *string        `json:"city,omitempty"`
	Country         *string        `json:"country,omitempty"`
	CreatedAt       *time.Time     `json:"created_at,omitempty"`
	Device          *string        `json:"device,omitempty"`
	DurationSeconds *float64       `json:"duration_seconds,omitempty"`
	EndAt           *time.Time     `json:"end_at,omitempty"`
	EventsCount     *float64       `json:"events_count,omitempty"`
	ExitPage        *string        `json:"exit_page,omitempty"`
	ID              *string        `json:"id,omitempty"`
	IsBounce        *bool          `json:"is_bounce,omitempty"`
	IsConversion    *bool          `json:"is_conversion,omitempty"`
	LandingPage     *string        `json:"landing_page,omitempty"`
	Medium          *string        `json:"medium,omitempty"`
	Os              *string        `json:"os,omitempty"`
	PageViews       *float64       `json:"page_views,omitempty"`
	PropertyID      *string        `json:"property_id,omitempty"`
	Raw             map[string]any `json:"raw,omitempty"`
	Source          *string        `json:"source,omitempty"`
	StartAt         *time.Time     `json:"start_at,omitempty"`
	UpdatedAt       *time.Time     `json:"updated_at,omitempty"`
	VisitorID       *string        `json:"visitor_id,omitempty"`
}

func (a AnalyticsSession) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AnalyticsSession) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AnalyticsSession) GetBrowser() *string {
	if a == nil {
		return nil
	}
	return a.Browser
}

func (a *AnalyticsSession) GetCampaign() *string {
	if a == nil {
		return nil
	}
	return a.Campaign
}

func (a *AnalyticsSession) GetCity() *string {
	if a == nil {
		return nil
	}
	return a.City
}

func (a *AnalyticsSession) GetCountry() *string {
	if a == nil {
		return nil
	}
	return a.Country
}

func (a *AnalyticsSession) GetCreatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreatedAt
}

func (a *AnalyticsSession) GetDevice() *string {
	if a == nil {
		return nil
	}
	return a.Device
}

func (a *AnalyticsSession) GetDurationSeconds() *float64 {
	if a == nil {
		return nil
	}
	return a.DurationSeconds
}

func (a *AnalyticsSession) GetEndAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.EndAt
}

func (a *AnalyticsSession) GetEventsCount() *float64 {
	if a == nil {
		return nil
	}
	return a.EventsCount
}

func (a *AnalyticsSession) GetExitPage() *string {
	if a == nil {
		return nil
	}
	return a.ExitPage
}

func (a *AnalyticsSession) GetID() *string {
	if a == nil {
		return nil
	}
	return a.ID
}

func (a *AnalyticsSession) GetIsBounce() *bool {
	if a == nil {
		return nil
	}
	return a.IsBounce
}

func (a *AnalyticsSession) GetIsConversion() *bool {
	if a == nil {
		return nil
	}
	return a.IsConversion
}

func (a *AnalyticsSession) GetLandingPage() *string {
	if a == nil {
		return nil
	}
	return a.LandingPage
}

func (a *AnalyticsSession) GetMedium() *string {
	if a == nil {
		return nil
	}
	return a.Medium
}

func (a *AnalyticsSession) GetOs() *string {
	if a == nil {
		return nil
	}
	return a.Os
}

func (a *AnalyticsSession) GetPageViews() *float64 {
	if a == nil {
		return nil
	}
	return a.PageViews
}

func (a *AnalyticsSession) GetPropertyID() *string {
	if a == nil {
		return nil
	}
	return a.PropertyID
}

func (a *AnalyticsSession) GetRaw() map[string]any {
	if a == nil {
		return nil
	}
	return a.Raw
}

func (a *AnalyticsSession) GetSource() *string {
	if a == nil {
		return nil
	}
	return a.Source
}

func (a *AnalyticsSession) GetStartAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.StartAt
}

func (a *AnalyticsSession) GetUpdatedAt() *time.Time {
	if a == nil {
		return nil
	}
	return a.UpdatedAt
}

func (a *AnalyticsSession) GetVisitorID() *string {
	if a == nil {
		return nil
	}
	return a.VisitorID
}
