// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CommerceMetadata struct {
	ExtraData map[string]any `json:"extra_data,omitempty"`
	ID        *string        `json:"id,omitempty"`
	Key       string         `json:"key"`
	Namespace *string        `json:"namespace,omitempty"`
	Type      *string        `json:"type,omitempty"`
	Value     map[string]any `json:"value,omitempty"`
}

func (o *CommerceMetadata) GetExtraData() map[string]any {
	if o == nil {
		return nil
	}
	return o.ExtraData
}

func (o *CommerceMetadata) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *CommerceMetadata) GetKey() string {
	if o == nil {
		return ""
	}
	return o.Key
}

func (o *CommerceMetadata) GetNamespace() *string {
	if o == nil {
		return nil
	}
	return o.Namespace
}

func (o *CommerceMetadata) GetType() *string {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *CommerceMetadata) GetValue() map[string]any {
	if o == nil {
		return nil
	}
	return o.Value
}
