// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

// Connection - A connection represents a specific authentication of an integration.
type Connection struct {
	// An authentication object that represents a specific authorized user's connection to an integration.
	Auth       *PropertyConnectionAuth `json:"auth,omitempty"`
	AuthAwsArn *string                 `json:"auth_aws_arn,omitempty"`
	// The Integration categories that this connection supports
	Categories      []PropertyConnectionCategories  `json:"categories"`
	CreatedAt       *time.Time                      `json:"created_at,omitempty"`
	Environment     *string                         `default:"Production" json:"environment"`
	ExternalXref    *string                         `json:"external_xref,omitempty"`
	ID              *string                         `json:"id,omitempty"`
	IntegrationName *string                         `json:"integration_name,omitempty"`
	IntegrationType string                          `json:"integration_type"`
	IsPaused        *bool                           `json:"is_paused,omitempty"`
	LastHealthyAt   *time.Time                      `json:"last_healthy_at,omitempty"`
	LastUnhealthyAt *time.Time                      `json:"last_unhealthy_at,omitempty"`
	Permissions     []PropertyConnectionPermissions `json:"permissions"`
	UpdatedAt       *time.Time                      `json:"updated_at,omitempty"`
	WorkspaceID     *string                         `json:"workspace_id,omitempty"`
}

func (c Connection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *Connection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *Connection) GetAuth() *PropertyConnectionAuth {
	if c == nil {
		return nil
	}
	return c.Auth
}

func (c *Connection) GetAuthAwsArn() *string {
	if c == nil {
		return nil
	}
	return c.AuthAwsArn
}

func (c *Connection) GetCategories() []PropertyConnectionCategories {
	if c == nil {
		return []PropertyConnectionCategories{}
	}
	return c.Categories
}

func (c *Connection) GetCreatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.CreatedAt
}

func (c *Connection) GetEnvironment() *string {
	if c == nil {
		return nil
	}
	return c.Environment
}

func (c *Connection) GetExternalXref() *string {
	if c == nil {
		return nil
	}
	return c.ExternalXref
}

func (c *Connection) GetID() *string {
	if c == nil {
		return nil
	}
	return c.ID
}

func (c *Connection) GetIntegrationName() *string {
	if c == nil {
		return nil
	}
	return c.IntegrationName
}

func (c *Connection) GetIntegrationType() string {
	if c == nil {
		return ""
	}
	return c.IntegrationType
}

func (c *Connection) GetIsPaused() *bool {
	if c == nil {
		return nil
	}
	return c.IsPaused
}

func (c *Connection) GetLastHealthyAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastHealthyAt
}

func (c *Connection) GetLastUnhealthyAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.LastUnhealthyAt
}

func (c *Connection) GetPermissions() []PropertyConnectionPermissions {
	if c == nil {
		return []PropertyConnectionPermissions{}
	}
	return c.Permissions
}

func (c *Connection) GetUpdatedAt() *time.Time {
	if c == nil {
		return nil
	}
	return c.UpdatedAt
}

func (c *Connection) GetWorkspaceID() *string {
	if c == nil {
		return nil
	}
	return c.WorkspaceID
}
