// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

type ContentType string

const (
	ContentTypeHTML     ContentType = "HTML"
	ContentTypeMarkdown ContentType = "MARKDOWN"
	ContentTypeText     ContentType = "TEXT"
	ContentTypeOther    ContentType = "OTHER"
)

func (e ContentType) ToPointer() *ContentType {
	return &e
}
func (e *ContentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "HTML":
		fallthrough
	case "MARKDOWN":
		fallthrough
	case "TEXT":
		fallthrough
	case "OTHER":
		*e = ContentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ContentType: %v", v)
	}
}

type KmsCommentType string

const (
	KmsCommentTypePageInline KmsCommentType = "PAGE_INLINE"
	KmsCommentTypePage       KmsCommentType = "PAGE"
)

func (e KmsCommentType) ToPointer() *KmsCommentType {
	return &e
}
func (e *KmsCommentType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PAGE_INLINE":
		fallthrough
	case "PAGE":
		*e = KmsCommentType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for KmsCommentType: %v", v)
	}
}

type KmsComment struct {
	Content     string          `json:"content"`
	ContentType *ContentType    `json:"content_type,omitempty"`
	CreatedAt   *time.Time      `json:"created_at,omitempty"`
	ID          *string         `json:"id,omitempty"`
	PageID      *string         `json:"page_id,omitempty"`
	ParentID    *string         `json:"parent_id,omitempty"`
	Raw         map[string]any  `json:"raw,omitempty"`
	Type        *KmsCommentType `json:"type,omitempty"`
	UpdatedAt   *time.Time      `json:"updated_at,omitempty"`
	UserID      *string         `json:"user_id,omitempty"`
}

func (k KmsComment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(k, "", false)
}

func (k *KmsComment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &k, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *KmsComment) GetContent() string {
	if o == nil {
		return ""
	}
	return o.Content
}

func (o *KmsComment) GetContentType() *ContentType {
	if o == nil {
		return nil
	}
	return o.ContentType
}

func (o *KmsComment) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *KmsComment) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *KmsComment) GetPageID() *string {
	if o == nil {
		return nil
	}
	return o.PageID
}

func (o *KmsComment) GetParentID() *string {
	if o == nil {
		return nil
	}
	return o.ParentID
}

func (o *KmsComment) GetRaw() map[string]any {
	if o == nil {
		return nil
	}
	return o.Raw
}

func (o *KmsComment) GetType() *KmsCommentType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *KmsComment) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

func (o *KmsComment) GetUserID() *string {
	if o == nil {
		return nil
	}
	return o.UserID
}
