// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

type LmsCourse struct {
	Categories    []string       `json:"categories,omitempty"`
	CreatedAt     *time.Time     `json:"created_at,omitempty"`
	Currency      *string        `json:"currency,omitempty"`
	Description   *string        `json:"description,omitempty"`
	ID            *string        `json:"id,omitempty"`
	InstructorIds []string       `json:"instructor_ids,omitempty"`
	IsActive      *bool          `json:"is_active,omitempty"`
	IsPrivate     *bool          `json:"is_private,omitempty"`
	Languages     []string       `json:"languages,omitempty"`
	Media         []LmsMedia     `json:"media,omitempty"`
	Name          string         `json:"name"`
	PriceAmount   *float64       `json:"price_amount,omitempty"`
	Raw           map[string]any `json:"raw,omitempty"`
	StudentIds    []string       `json:"student_ids,omitempty"`
	UpdatedAt     *time.Time     `json:"updated_at,omitempty"`
}

func (l LmsCourse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LmsCourse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"name"}); err != nil {
		return err
	}
	return nil
}

func (o *LmsCourse) GetCategories() []string {
	if o == nil {
		return nil
	}
	return o.Categories
}

func (o *LmsCourse) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *LmsCourse) GetCurrency() *string {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *LmsCourse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *LmsCourse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *LmsCourse) GetInstructorIds() []string {
	if o == nil {
		return nil
	}
	return o.InstructorIds
}

func (o *LmsCourse) GetIsActive() *bool {
	if o == nil {
		return nil
	}
	return o.IsActive
}

func (o *LmsCourse) GetIsPrivate() *bool {
	if o == nil {
		return nil
	}
	return o.IsPrivate
}

func (o *LmsCourse) GetLanguages() []string {
	if o == nil {
		return nil
	}
	return o.Languages
}

func (o *LmsCourse) GetMedia() []LmsMedia {
	if o == nil {
		return nil
	}
	return o.Media
}

func (o *LmsCourse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *LmsCourse) GetPriceAmount() *float64 {
	if o == nil {
		return nil
	}
	return o.PriceAmount
}

func (o *LmsCourse) GetRaw() map[string]any {
	if o == nil {
		return nil
	}
	return o.Raw
}

func (o *LmsCourse) GetStudentIds() []string {
	if o == nil {
		return nil
	}
	return o.StudentIds
}

func (o *LmsCourse) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
