// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

type LmsStudent struct {
	Address    *PropertyLmsStudentAddress `json:"address,omitempty"`
	CreatedAt  *time.Time                 `json:"created_at,omitempty"`
	Emails     []LmsEmail                 `json:"emails,omitempty"`
	FirstName  *string                    `json:"first_name,omitempty"`
	ID         *string                    `json:"id,omitempty"`
	ImageURL   *string                    `json:"image_url,omitempty"`
	LastName   *string                    `json:"last_name,omitempty"`
	Name       *string                    `json:"name,omitempty"`
	Raw        map[string]any             `json:"raw,omitempty"`
	Telephones []LmsTelephone             `json:"telephones,omitempty"`
	UpdatedAt  *time.Time                 `json:"updated_at,omitempty"`
}

func (l LmsStudent) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LmsStudent) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LmsStudent) GetAddress() *PropertyLmsStudentAddress {
	if l == nil {
		return nil
	}
	return l.Address
}

func (l *LmsStudent) GetCreatedAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.CreatedAt
}

func (l *LmsStudent) GetEmails() []LmsEmail {
	if l == nil {
		return nil
	}
	return l.Emails
}

func (l *LmsStudent) GetFirstName() *string {
	if l == nil {
		return nil
	}
	return l.FirstName
}

func (l *LmsStudent) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LmsStudent) GetImageURL() *string {
	if l == nil {
		return nil
	}
	return l.ImageURL
}

func (l *LmsStudent) GetLastName() *string {
	if l == nil {
		return nil
	}
	return l.LastName
}

func (l *LmsStudent) GetName() *string {
	if l == nil {
		return nil
	}
	return l.Name
}

func (l *LmsStudent) GetRaw() map[string]any {
	if l == nil {
		return nil
	}
	return l.Raw
}

func (l *LmsStudent) GetTelephones() []LmsTelephone {
	if l == nil {
		return nil
	}
	return l.Telephones
}

func (l *LmsStudent) GetUpdatedAt() *time.Time {
	if l == nil {
		return nil
	}
	return l.UpdatedAt
}
