// Code generated by Speakeasy (https://speakeasyapi.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type PropertyPropertyIntegrationSupportWebhookEventsDeleted string

const (
	PropertyPropertyIntegrationSupportWebhookEventsDeletedVirtual PropertyPropertyIntegrationSupportWebhookEventsDeleted = "virtual"
	PropertyPropertyIntegrationSupportWebhookEventsDeletedNative  PropertyPropertyIntegrationSupportWebhookEventsDeleted = "native"
)

func (e PropertyPropertyIntegrationSupportWebhookEventsDeleted) ToPointer() *PropertyPropertyIntegrationSupportWebhookEventsDeleted {
	return &e
}
func (e *PropertyPropertyIntegrationSupportWebhookEventsDeleted) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "virtual":
		fallthrough
	case "native":
		*e = PropertyPropertyIntegrationSupportWebhookEventsDeleted(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PropertyPropertyIntegrationSupportWebhookEventsDeleted: %v", v)
	}
}
