// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PropertyAdsGroupTargetingPlacement struct {
	AudienceNetworkPositions []string `json:"audience_network_positions,omitempty"`
	FacebookPositions        []string `json:"facebook_positions,omitempty"`
	InstagramPositions       []string `json:"instagram_positions,omitempty"`
	MessengerPositions       []string `json:"messenger_positions,omitempty"`
	Platforms                []string `json:"platforms,omitempty"`
}

func (p *PropertyAdsGroupTargetingPlacement) GetAudienceNetworkPositions() []string {
	if p == nil {
		return nil
	}
	return p.AudienceNetworkPositions
}

func (p *PropertyAdsGroupTargetingPlacement) GetFacebookPositions() []string {
	if p == nil {
		return nil
	}
	return p.FacebookPositions
}

func (p *PropertyAdsGroupTargetingPlacement) GetInstagramPositions() []string {
	if p == nil {
		return nil
	}
	return p.InstagramPositions
}

func (p *PropertyAdsGroupTargetingPlacement) GetMessengerPositions() []string {
	if p == nil {
		return nil
	}
	return p.MessengerPositions
}

func (p *PropertyAdsGroupTargetingPlacement) GetPlatforms() []string {
	if p == nil {
		return nil
	}
	return p.Platforms
}
