// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ScimManagerType string

const (
	ScimManagerTypeDirect   ScimManagerType = "direct"
	ScimManagerTypeIndirect ScimManagerType = "indirect"
)

func (e ScimManagerType) ToPointer() *ScimManagerType {
	return &e
}

// ScimManager - "id" attribute of another User.
type ScimManager struct {
	DollarRef   *string          `json:"$ref,omitempty"`
	DisplayName *string          `json:"displayName,omitempty"`
	ManagerID   *string          `json:"managerId,omitempty"`
	Type        *ScimManagerType `json:"type,omitempty"`
	Value       *string          `json:"value,omitempty"`
}

func (s *ScimManager) GetDollarRef() *string {
	if s == nil {
		return nil
	}
	return s.DollarRef
}

func (s *ScimManager) GetDisplayName() *string {
	if s == nil {
		return nil
	}
	return s.DisplayName
}

func (s *ScimManager) GetManagerID() *string {
	if s == nil {
		return nil
	}
	return s.ManagerID
}

func (s *ScimManager) GetType() *ScimManagerType {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *ScimManager) GetValue() *string {
	if s == nil {
		return nil
	}
	return s.Value
}
