// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/unified-to/unified-go-sdk/pkg/utils"
	"time"
)

type ReturnType string

const (
	ReturnTypeCustomer  ReturnType = "CUSTOMER"
	ReturnTypeVendor    ReturnType = "VENDOR"
	ReturnTypeWarranty  ReturnType = "WARRANTY"
	ReturnTypeDefective ReturnType = "DEFECTIVE"
	ReturnTypeOther     ReturnType = "OTHER"
)

func (e ReturnType) ToPointer() *ReturnType {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ReturnType) IsExact() bool {
	if e != nil {
		switch *e {
		case "CUSTOMER", "VENDOR", "WARRANTY", "DEFECTIVE", "OTHER":
			return true
		}
	}
	return false
}

type ShippingShipmentStatus string

const (
	ShippingShipmentStatusPending           ShippingShipmentStatus = "PENDING"
	ShippingShipmentStatusProcessing        ShippingShipmentStatus = "PROCESSING"
	ShippingShipmentStatusInTransit         ShippingShipmentStatus = "IN_TRANSIT"
	ShippingShipmentStatusDelivered         ShippingShipmentStatus = "DELIVERED"
	ShippingShipmentStatusException         ShippingShipmentStatus = "EXCEPTION"
	ShippingShipmentStatusCancelled         ShippingShipmentStatus = "CANCELLED"
	ShippingShipmentStatusLabelCreated      ShippingShipmentStatus = "LABEL_CREATED"
	ShippingShipmentStatusPickedUp          ShippingShipmentStatus = "PICKED_UP"
	ShippingShipmentStatusOutForDelivery    ShippingShipmentStatus = "OUT_FOR_DELIVERY"
	ShippingShipmentStatusDeliveryAttempted ShippingShipmentStatus = "DELIVERY_ATTEMPTED"
	ShippingShipmentStatusReturnedToSender  ShippingShipmentStatus = "RETURNED_TO_SENDER"
	ShippingShipmentStatusHeldAtLocation    ShippingShipmentStatus = "HELD_AT_LOCATION"
	ShippingShipmentStatusCustomsClearance  ShippingShipmentStatus = "CUSTOMS_CLEARANCE"
	ShippingShipmentStatusExceptionResolved ShippingShipmentStatus = "EXCEPTION_RESOLVED"
)

func (e ShippingShipmentStatus) ToPointer() *ShippingShipmentStatus {
	return &e
}

// IsExact returns true if the value matches a known enum value, false otherwise.
func (e *ShippingShipmentStatus) IsExact() bool {
	if e != nil {
		switch *e {
		case "PENDING", "PROCESSING", "IN_TRANSIT", "DELIVERED", "EXCEPTION", "CANCELLED", "LABEL_CREATED", "PICKED_UP", "OUT_FOR_DELIVERY", "DELIVERY_ATTEMPTED", "RETURNED_TO_SENDER", "HELD_AT_LOCATION", "CUSTOMS_CLEARANCE", "EXCEPTION_RESOLVED":
			return true
		}
	}
	return false
}

type ShippingShipment struct {
	CarrierID *string    `json:"carrier_id,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// Customs information
	Customs *PropertyShippingShipmentCustoms `json:"customs,omitempty"`
	// Origin address
	FromAddress *PropertyShippingShipmentFromAddress `json:"from_address,omitempty"`
	ID          *string                              `json:"id,omitempty"`
	// Insurance details
	Insurance                *PropertyShippingShipmentInsurance `json:"insurance,omitempty"`
	IsAdultSignatureRequired *bool                              `json:"is_adult_signature_required,omitempty"`
	IsInternational          *bool                              `json:"is_international,omitempty"`
	IsRateGuaranteed         *bool                              `json:"is_rate_guaranteed,omitempty"`
	IsReturn                 *bool                              `json:"is_return,omitempty"`
	IsSignatureRequired      *bool                              `json:"is_signature_required,omitempty"`
	LabelID                  *string                            `json:"label_id,omitempty"`
	OrderID                  *string                            `json:"order_id,omitempty"`
	OriginalShipmentID       *string                            `json:"original_shipment_id,omitempty"`
	// Array of packages in this shipment
	Packages                []ShippingPackage `json:"packages,omitempty"`
	RateAmount              *float64          `json:"rate_amount,omitempty"`
	RateCurrency            *string           `json:"rate_currency,omitempty"`
	RateEstimatedDays       *float64          `json:"rate_estimated_days,omitempty"`
	RateEstimatedDeliveryAt *time.Time        `json:"rate_estimated_delivery_at,omitempty"`
	RateID                  *string           `json:"rate_id,omitempty"`
	RateServiceName         *string           `json:"rate_service_name,omitempty"`
	Raw                     map[string]any    `json:"raw,omitempty"`
	ReferenceNumber         *string           `json:"reference_number,omitempty"`
	// Return address (may differ from from_address)
	ReturnAddress             *PropertyShippingShipmentReturnAddress `json:"return_address,omitempty"`
	ReturnAuthorizationNumber *string                                `json:"return_authorization_number,omitempty"`
	ReturnReason              *string                                `json:"return_reason,omitempty"`
	ReturnType                *ReturnType                            `json:"return_type,omitempty"`
	ServiceCode               *string                                `json:"service_code,omitempty"`
	ShippedAt                 *time.Time                             `json:"shipped_at,omitempty"`
	// Array of special instructions
	SpecialInstructions []string                `json:"special_instructions,omitempty"`
	Status              *ShippingShipmentStatus `json:"status,omitempty"`
	// Destination address
	ToAddress             *PropertyShippingShipmentToAddress `json:"to_address,omitempty"`
	TrackingID            *string                            `json:"tracking_id,omitempty"`
	UpdatedAt             *time.Time                         `json:"updated_at,omitempty"`
	WarehouseLocationID   *string                            `json:"warehouse_location_id,omitempty"`
	WarehouseLocationName *string                            `json:"warehouse_location_name,omitempty"`
}

func (s ShippingShipment) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *ShippingShipment) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (s *ShippingShipment) GetCarrierID() *string {
	if s == nil {
		return nil
	}
	return s.CarrierID
}

func (s *ShippingShipment) GetCreatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.CreatedAt
}

func (s *ShippingShipment) GetCustoms() *PropertyShippingShipmentCustoms {
	if s == nil {
		return nil
	}
	return s.Customs
}

func (s *ShippingShipment) GetFromAddress() *PropertyShippingShipmentFromAddress {
	if s == nil {
		return nil
	}
	return s.FromAddress
}

func (s *ShippingShipment) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ShippingShipment) GetInsurance() *PropertyShippingShipmentInsurance {
	if s == nil {
		return nil
	}
	return s.Insurance
}

func (s *ShippingShipment) GetIsAdultSignatureRequired() *bool {
	if s == nil {
		return nil
	}
	return s.IsAdultSignatureRequired
}

func (s *ShippingShipment) GetIsInternational() *bool {
	if s == nil {
		return nil
	}
	return s.IsInternational
}

func (s *ShippingShipment) GetIsRateGuaranteed() *bool {
	if s == nil {
		return nil
	}
	return s.IsRateGuaranteed
}

func (s *ShippingShipment) GetIsReturn() *bool {
	if s == nil {
		return nil
	}
	return s.IsReturn
}

func (s *ShippingShipment) GetIsSignatureRequired() *bool {
	if s == nil {
		return nil
	}
	return s.IsSignatureRequired
}

func (s *ShippingShipment) GetLabelID() *string {
	if s == nil {
		return nil
	}
	return s.LabelID
}

func (s *ShippingShipment) GetOrderID() *string {
	if s == nil {
		return nil
	}
	return s.OrderID
}

func (s *ShippingShipment) GetOriginalShipmentID() *string {
	if s == nil {
		return nil
	}
	return s.OriginalShipmentID
}

func (s *ShippingShipment) GetPackages() []ShippingPackage {
	if s == nil {
		return nil
	}
	return s.Packages
}

func (s *ShippingShipment) GetRateAmount() *float64 {
	if s == nil {
		return nil
	}
	return s.RateAmount
}

func (s *ShippingShipment) GetRateCurrency() *string {
	if s == nil {
		return nil
	}
	return s.RateCurrency
}

func (s *ShippingShipment) GetRateEstimatedDays() *float64 {
	if s == nil {
		return nil
	}
	return s.RateEstimatedDays
}

func (s *ShippingShipment) GetRateEstimatedDeliveryAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.RateEstimatedDeliveryAt
}

func (s *ShippingShipment) GetRateID() *string {
	if s == nil {
		return nil
	}
	return s.RateID
}

func (s *ShippingShipment) GetRateServiceName() *string {
	if s == nil {
		return nil
	}
	return s.RateServiceName
}

func (s *ShippingShipment) GetRaw() map[string]any {
	if s == nil {
		return nil
	}
	return s.Raw
}

func (s *ShippingShipment) GetReferenceNumber() *string {
	if s == nil {
		return nil
	}
	return s.ReferenceNumber
}

func (s *ShippingShipment) GetReturnAddress() *PropertyShippingShipmentReturnAddress {
	if s == nil {
		return nil
	}
	return s.ReturnAddress
}

func (s *ShippingShipment) GetReturnAuthorizationNumber() *string {
	if s == nil {
		return nil
	}
	return s.ReturnAuthorizationNumber
}

func (s *ShippingShipment) GetReturnReason() *string {
	if s == nil {
		return nil
	}
	return s.ReturnReason
}

func (s *ShippingShipment) GetReturnType() *ReturnType {
	if s == nil {
		return nil
	}
	return s.ReturnType
}

func (s *ShippingShipment) GetServiceCode() *string {
	if s == nil {
		return nil
	}
	return s.ServiceCode
}

func (s *ShippingShipment) GetShippedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.ShippedAt
}

func (s *ShippingShipment) GetSpecialInstructions() []string {
	if s == nil {
		return nil
	}
	return s.SpecialInstructions
}

func (s *ShippingShipment) GetStatus() *ShippingShipmentStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *ShippingShipment) GetToAddress() *PropertyShippingShipmentToAddress {
	if s == nil {
		return nil
	}
	return s.ToAddress
}

func (s *ShippingShipment) GetTrackingID() *string {
	if s == nil {
		return nil
	}
	return s.TrackingID
}

func (s *ShippingShipment) GetUpdatedAt() *time.Time {
	if s == nil {
		return nil
	}
	return s.UpdatedAt
}

func (s *ShippingShipment) GetWarehouseLocationID() *string {
	if s == nil {
		return nil
	}
	return s.WarehouseLocationID
}

func (s *ShippingShipment) GetWarehouseLocationName() *string {
	if s == nil {
		return nil
	}
	return s.WarehouseLocationName
}
