// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TicketingTelephoneType string

const (
	TicketingTelephoneTypeWork   TicketingTelephoneType = "WORK"
	TicketingTelephoneTypeHome   TicketingTelephoneType = "HOME"
	TicketingTelephoneTypeOther  TicketingTelephoneType = "OTHER"
	TicketingTelephoneTypeFax    TicketingTelephoneType = "FAX"
	TicketingTelephoneTypeMobile TicketingTelephoneType = "MOBILE"
)

func (e TicketingTelephoneType) ToPointer() *TicketingTelephoneType {
	return &e
}

type TicketingTelephone struct {
	Telephone string                  `json:"telephone"`
	Type      *TicketingTelephoneType `json:"type,omitempty"`
}

func (o *TicketingTelephone) GetTelephone() string {
	if o == nil {
		return ""
	}
	return o.Telephone
}

func (o *TicketingTelephone) GetType() *TicketingTelephoneType {
	if o == nil {
		return nil
	}
	return o.Type
}
