// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// UcContact - A contact represents a person that optionally is associated with a call
type UcContact struct {
	Company   *string    `json:"company,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// An array of email addresses for this contact
	Emails []UcEmail `json:"emails,omitempty"`
	ID     *string   `json:"id,omitempty"`
	Name   *string   `json:"name,omitempty"`
	// The raw data returned by the integration for this contact
	Raw *PropertyUcContactRaw `json:"raw,omitempty"`
	// An array of telephones for this contact
	Telephones []UcTelephone `json:"telephones,omitempty"`
	Title      *string       `json:"title,omitempty"`
	UpdatedAt  *time.Time    `json:"updated_at,omitempty"`
}

func (o *UcContact) GetCompany() *string {
	if o == nil {
		return nil
	}
	return o.Company
}

func (o *UcContact) GetCreatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *UcContact) GetEmails() []UcEmail {
	if o == nil {
		return nil
	}
	return o.Emails
}

func (o *UcContact) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UcContact) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UcContact) GetRaw() *PropertyUcContactRaw {
	if o == nil {
		return nil
	}
	return o.Raw
}

func (o *UcContact) GetTelephones() []UcTelephone {
	if o == nil {
		return nil
	}
	return o.Telephones
}

func (o *UcContact) GetTitle() *string {
	if o == nil {
		return nil
	}
	return o.Title
}

func (o *UcContact) GetUpdatedAt() *time.Time {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
