workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://api.unified.to/openapi.json
        registry:
            location: registry.speakeasyapi.dev/unified/unified/my-source
targets:
    go-terget:
        target: go
        source: my-source
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/unified/unified/my-source-go-code-samples
            blocking: false
